### ISSUE TITLE
Websocket disconnections and proper configuration

### ISSUE THREAD

**Issue by Radek44** [mesosphere/marathon-lb#105]
When using marathon-lb to route a websocket connection we observe disconnections after a few seconds. I assume this is a setting that is configurable - how to go about persisting an established websocket connection through marathon-lb?

As an aside, how does the round-robin algorithm work when multiple instances of a service are available in the case of websockets?

**Comment by brndnmtthws** [comment]
Are you using any other LB in front of MLB? Such as an ELB?

Marathon-lb _should_ work fine with websockets without any changes, but if you use an ELB in HTTP mode it will not work.

Anyway, please reopen if this is still an issue.

**Comment by richardgirges** [comment]
@brndnmtthws I'm running marathon-lb behind ELB and have discovered that this combination doesn't work. Curious as to _why_ this is problematic?

We're using ELB to route HTTPS traffic to an HTTP-only marathon-lb instance. Essentially we're following the example in this blog article: https://mesosphere.com/blog/2015/12/04/dcos-marathon-lb/

Are any workarounds to get websockets working with a marathon-lb + ELB setup?

**Comment by brndnmtthws** [comment]
Is the ELB configured in HTTP or TCP mode? Last I heard the ELB won't work well with websockets, but it might if you run it in TCP mode.

**Comment by richardgirges** [comment]
Thanks for the response. 

Actually the initial issue I was facing turned out to be a websocket-related bug in my application code. User error! 

I was able to get websockets working with both the new AWS Application LB and Classic LB utilizing HTTP routing (not TCP) to marathon-lb on a DC/OS public agent node without any additional setup!

**Comment by willastronomer** [comment]
Will enabling application sticky sessions on the http elb correct the issue?

**Comment by cs94njw** [comment]
@richardgirges What was the bug you had?  We're having these disconnections and I'd like to ensure I'm not falling into silly bugs.

**Comment by richardgirges** [comment]
@cs94njw for my specific problem it was that I wasn't sending a websocket ping from my client to my socket.io server. Upon setting a ping with a 10 second interval, the disconnects stopped.

**Comment by cs94njw** [comment]
That is awesome - thank you so much for replying!
