### ISSUE TITLE
Add host header HTTP 301 redirect

### ISSUE THREAD

**Issue by mpherg** [mesosphere/marathon-lb#117]
It would be nice to be able to define an HTTP frontend 301 redirect based on a host header, like this:

    redirect prefix <vhost> code 301 if { HDR{host} -i <redirected-host> }

For example, if my backend requires the host header to be a FQDN, I can redirect "http://service/" to "http://service.my.purple.com/" before hitting the backend.

I can't figure out how to do this in marathon-lb. I'm no Python expert, but to me it looks like this isn't possible (yet).

**Comment by brndnmtthws** [comment]
You could hijack the HTTP to HTTPS redirect, like this:

```json
  "labels":{
    "HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS":"  redirect prefix service.my.purple.com code 301 if hdr{host} -i service",
    "HAPROXY_0_REDIRECT_TO_HTTPS":"true",
    "HAPROXY_0_VHOST":"service,service.my.purple.com",
    "HAPROXY_GROUP":"external"
  }
}
