### ISSUE TITLE
virtual hosts are not properly handled on HTTP

### ISSUE THREAD

**Issue by theely** [mesosphere/marathon-lb#125]
Looks like that on HTTP the load balancer is not correctly distinguishing between virtual hosts.
For example if we configure two apps with:

--------------------------------------------------------
app 1: 
HAPROXY_GROUP=external
HAPROXY_0_VHOST=example.com
HAPROXY_0_PORT=80

app 2:
HAPROXY_GROUP=external
HAPROXY_0_VHOST=api.example.com   (note the addition of api.)
HAPROXY_0_PORT=80

with the load balancer:
I am using the official docker container by mesosphere managed via marathon with following settings:
{
  "type": "DOCKER",
  "docker": {
    "image": "mesosphere/marathon-lb:latest",
    "network": "HOST",
    "forcePullImage": true
  }
}
required ports are 80,443 and the env variable HAPROXY_SSL_CERT has been set.

--------------------------------------------------------

By trying to call http://api.example.com the load balancer will round robin over app 1 or app 2.
I would expect the load balancer to always cal app 2.

NOTE: the same configuration using HTTPS works like a charm, the cal is always routed to app 2.

**Comment by theely** [comment]
p.s. it looks like that by loading http://ip-of-the-loadbalancer app 1 and app 2 are randomly picked I would expect to always get "503 Service Unavailable" as no hostname is defined in the http request.

**Comment by brndnmtthws** [comment]
Hmm, could you share the haproxy config? By default marathon-lb uses `acl ... hdr(host) ...` which, according to the docs, should be an _exact_ match. See: https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#7.3.6-req.hdr

You can grab the config with `curl http://marathon-lb.marathon.mesos:9090/_haproxy_getconfig` on recent versions.

**Comment by brndnmtthws** [comment]
Oh, actually, I just realized what's happening. You're using `HAPROXY_0_PORT=80` which tells haproxy to bind directly to that port. Drop that label and you should be fine.

**Comment by pocharlies** [comment]
Hello guys. 

Looking for this error, i found that zdd.py blue-green deployment script put haproxy_0_port=80 label on every deploy, broking all another host connected to marathon-lb.
