### ISSUE TITLE
how can I add stats page?

### ISSUE THREAD

**Issue by perfe1983** [mesosphere/marathon-lb#126]
how can I enable stats page?

I must  add 
**stats uri /**

after this block

    listen stats
      bind 0.0.0.0:9090
      balance
      mode http
      stats enable
      monitor-uri /_haproxy_health_check
      acl getpid path /_haproxy_getpids
      http-request use-service lua.getpids if getpid
      acl getconfig path /_haproxy_getconfig
      http-request use-service lua.getconfig if getconfig

or there is another way?
tks
Luca

**Comment by pgraemer** [comment]
the stats page is enabled by default. the default URI is **/haproxy?stats** as mentioned in the docs. 
If you need to change that uri make use of the template HAPROXY_HEAD.

**Comment by perfe1983** [comment]
tks for the answer
