### ISSUE TITLE
Support nested paths

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon-lb#131]
Marathon-lb currently uses the `path_beg` syntax for evaluating paths; can we change to or enable an option for `path_reg` syntax to allow nested paths?

**Comment by mikestaub** [comment]
I created a PR to fix this. I should be able to provide a custom HAPROXY_0_HTTP_FRONTEND_ACL_WITH_PATH template via labels, but the code was simply not reading it from my config.

**Comment by mikestaub** [comment]
This has been resolved by #133

**Comment by brndnmtthws** [comment]
As per https://github.com/mesosphere/marathon-lb/issues/131#issuecomment-204579533, you can customize the behaviour with templates if needed.
