### ISSUE TITLE
Overridable templates example from README does not work

### ISSUE THREAD

**Issue by rvalkenaers** [mesosphere/marathon-lb#140]
I'm trying to use the example to override HAPROXY_0_BACKEND_HTTP_OPTIONS from the README but the config validation fails (I'm using the latest docker image):

[ALERT] 096/091135 (164) : parsing [/tmp/tmp1207best:178] : unknown option 'forwardfor
'.
[ALERT] 096/091135 (164) : Error(s) found in configuration file : /tmp/tmp1207best
[ALERT] 096/091135 (164) : Fatal errors found in configuration.

For clarity I'm using this label:
"HAPROXY_0_BACKEND_HTTP_OPTIONS"=" option forwardfor\n no option http-keep-alive\n http-request set-header X-Forwarded-Port %[dst_port]\n http-request add-header X-Forwarded-Proto https if { ssl_fc }\n"

**Comment by rohit01** [comment]
I was able to set this up using API. Is it working from API?

**Comment by rvalkenaers** [comment]
It does indeed seems to work from the API.

Thanks.
