### ISSUE TITLE
Adding "timeout server Ns" to backend configuration

### ISSUE THREAD

**Issue by joerwin** [mesosphere/marathon-lb#147]
I am trying to understand which label I should use to add add a "timeout server Nms" to the backend in HAProxy. this is documented in HA proxy as a valid configuration for defaults, listen and backends. 

I tried specifying:
HAPROXY_0_BACKEND_HTTP_OPTIONS as "timeout server Nms"

but I am not seeing the values in the confiuration.

**Comment by brndnmtthws** [comment]
You probably want something like this:

```json
"labels": {
  "HAPROXY_0_BACKEND_HEAD": "backend {backend}\r\n  balance {balance}\r\n  mode {mode}\r\n  timeout server 1000ms"
}
```

**Comment by Arkan** [comment]
I had the same issue, and I had to put a "\n" at the end otherwise Haproxy failed to load the config.

**Comment by brndnmtthws** [comment]
I added a section to the wiki for this: https://github.com/mesosphere/marathon-lb/wiki#setting-timeout-for-long-lived-socket-connections
