### ISSUE TITLE
[Feature Request] Please provide a way to support wildcard vhost(s) for HTTP and HTTPS

### ISSUE THREAD

**Issue by gena01** [mesosphere/marathon-lb#161]
Right now we can set vhost for an app in marathon. Unfortunately i haven't found a way to add a wildcard vhost to either HTTP (port 80) or HTTPS (port 443). I know i can feed it a wildcard cert, but actually handling the routing is missing?

**Comment by brndnmtthws** [comment]
You can override the appropriate label to use a regex (see https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#7.3.6-req.hdr), like this:

```json
"labels": {
  "HAPROXY_0_HTTP_FRONTEND_ACL": "  acl host_{cleanedUpHostname} hdr_reg(host) -i {hostname}\n  use_backend {backend} if host_{cleanedUpHostname}\n"
}
```

**Comment by gena01** [comment]
This is great, but I am trying to setup wildcard to run after exact matches have been done first. So the wildcard always needs to be the last thing on the ACL list.

**Comment by brndnmtthws** [comment]
There's a weight parameter, which you could set it to -1:

```json
"labels": {
  "HAPROXY_0_BACKEND_WEIGHT": "-1"
}
```
