### ISSUE TITLE
[Feature Request] Please provide a way to enable 'option httplog' for frontend

### ISSUE THREAD

**Issue by gena01** [mesosphere/marathon-lb#162]
Would be nice to be able to use HTTP log format from HAProxy. 

I can sort of hack around it when going through port 80. Things get a bit more tricky on the service port side since the mode is a template that can be either tcp or http.

**Comment by brndnmtthws** [comment]
You can pass your own frontend template:

```json
"labels": {
  "HAPROXY_FRONTEND_HEAD": "frontend {backend}\n  bind {bindAddr}:{servicePort}{sslCert}{bindOptions}\n  mode {mode}\n  option httplog\n"
}
```

**Comment by gena01** [comment]
I tried putting that label in through Marathon UI and it looked like \n were used as text, breaking haproxy.cfg. What am I missing? I am using marathon-lb 1.1.3

**Comment by brndnmtthws** [comment]
The Marathon UI will eat the `\n` characters, so you'll have to either use the JSON editor in recent versions, or the API.

**Comment by gena01** [comment]
:( This might be problematic. This bug was closed on the marathon UI side: https://github.com/mesosphere/marathon/issues/3734 to support multiple lines.

Is it possible to somehow allow \n as 2 characters in the marathon config and then do some sort of search/replace in marathon-lb?

**Comment by brndnmtthws** [comment]
I commented on the issue over there. There's nothing to be done as far as marathon-lb is concerned.
