### ISSUE TITLE
Use TASK_KILLING state to suppress backends

### ISSUE THREAD

**Issue by tadanki** [mesosphere/marathon-lb#163]
This is a proposal for fixing an issue people have reported a few times earlier: like #129 

I requested the update of Marathon to allow to propagate the TASK_KILLING state offered by Mesos 0.28. This is already moving and should be available really soon on Marathon (nightly or next build). 

Running Marathon with the TASK_KILLING feature enabled, allows us to now listen for that event to show up on the subscription of events and to use this information to suppress the generation of backends  on reload. We have built this out and looks decent in our tests. For those running docker containers, it is possible to delay the termination of the container by using Mesos Slave Option: --docker_stop_timeout=5s  to accord marathon-lb's reload enough time to completely drain before letting the docker container die.

Wondering if this fix is along the lines that you guys are thinking (?). I ll try to get a pull request in soon so I can get some eyes on this.

**Comment by brndnmtthws** [comment]
This actually _doesn't_ fix the problem, but it's good to have anyway.

**Comment by tadanki** [comment]
@brndnmtthws Interesting, could you please elaborate as to why this might not fix the problem ?

**Comment by brndnmtthws** [comment]
It's probabilistic. You're not guaranteed to drain tasks completely before terminating the backend.

The safe way to do it is to drain tasks _before_ attempting to kill them, which is [how this works](https://github.com/mesosphere/marathon-lb#zero-downtime-deployments).

**Comment by brndnmtthws** [comment]
By the way, Marathon doesn't actually surface this data yet. Once it's available, I can add support for it.

**Comment by tadanki** [comment]
Here is the requested fix on the Marathon project: https://github.com/mesosphere/marathon/issues/3813

Agreed, that is a good strategy for rolling out updates. Our scenario is far simpler: scaling the service. As we respond to simple waxing and waning traffic patterns, our scaling heuristic implements a corresponding scaling action and we end up with some dropped requests due to the fact that our docker containers die early. 

Currently, TASK_KILLED is generated as the SIGKILL is sent to the docker container not when the first attempted SIGTERM is sent. Thus, even though our deployment of marathon-lb runs in sse mode, it is already too late by the time it sees the message. With significant traffic, we drop a non trivial amount on the floor. 

As TASK_KILLING is being generated as soon as the attempt to kill the task begins, we can use the docker_stop_timeout to create a time lag before the kill happens. I currently suppress the backend from being generated after the call to get_apps in marathon_lb.py. If it is preferred instead to create the backend with draining set to true, I can do that instead.

**Comment by brndnmtthws** [comment]
Yeah, I'm with you. I think it's an improvement, but it's not a cure-all solution. I'm just trying to manage people's expectations.

**Comment by lloesche** [comment]
@tadanki you might also be interested in Kill Policies which will land in Mesos 0.29:
https://docs.google.com/presentation/d/1xzlGLc1rKwoW-ocDSKOJSmtUwMCtVWczjAKeSVnjegA/edit
https://issues.apache.org/jira/browse/MESOS-4909

**Comment by kholloway** [comment]
TASK_KILLING is available in Marathon 1.3.0 and higher, can this issue be re-opened now that support for it is available in Marathon?

**Comment by brndnmtthws** [comment]
It's already supported, however it's a kludge at best for supporting proper
backend draining.

**Comment by kholloway** [comment]
Thanks for the quick reply, I see now that you already handle any 'status_update_event' so yeah all good and I agree it's a kludge. :)

Thanks! 👍
