### ISSUE TITLE
Multiple marathon-lb in the same mesos agent

### ISSUE THREAD

**Issue by h0tbird** [mesosphere/marathon-lb#166]
I am trying to run `marathon-lb-ext` and `marathon-lb-int` in the same mesos agent.
Unfortunately both are binding to ports 9090 and 9091.
I need the ability to define different ports for each `marathon-lb`.
The `ext` also binds to `80` and `443` and is only used for vhosts.
The `int` is only used for backends.

**Comment by h0tbird** [comment]
Also setting `--env PORTS=9090,9091` and `--env PORTS=9190,9191` seems useless.

**Comment by brndnmtthws** [comment]
Marathon-lb is really not intended to be used this way.
