### ISSUE TITLE
Any supported way to customize haproxy's 503 page?

### ISSUE THREAD

**Issue by dpgeekzero** [mesosphere/marathon-lb#171]
When I was rolling my own haproxy container I had customized the 503 page so my users would freak out a bit less.  It also gave me a nice way to provide support/helpdesk info.

I'm loving marathon-lb, much better than the mess I had; but how can I customize the error pages?

**Comment by lloesche** [comment]
Hi,

if you look at https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md you will find a list of templates, most of which can be overridden. Either by providing a file of the same name as the template in the templates/ directory or using a Marathon label on a app by app basis.

So what should be possible (I haven't tried it though) is that you override HAPROXY_HEAD  or HAPROXY_FRONTEND_HEAD or HAPROXY_BACKEND_HEAD depending on whether you want to set the custom 503 page globally, on the frontend or on the backend.

For instance if we wanted to override the frontend we could either create a file `templates/HAPROXY_FRONTEND_HEAD` to override all frontends or set a label `HAPROXY_{n}_FRONTEND_HEAD` on a single Marathon app (where `{n}` is the service port index), to override only the error files of a specific app.

The contents of the template would look something like this:
```
frontend {backend}
  bind {bindAddr}:{servicePort}{sslCert}{bindOptions}
  mode {mode}
  errorfile 503 /errorfiles/503.http
```

/errorfiles/ would be the directory where you volume mount your custom errorfiles into (if you're using marathon-lb as a Docker container).

**Comment by jodem** [comment]
Hi,

I have not tested yet but it's part of a story we are going to implement. Here is what we will try :

Create a template to update the frontend marathon_https_in section. Make sure you have at the end of the section this rule to handle any unmatched ACL :

` default_backend custom503 `

2 : add in the global template the default backend that redirect to the expected error page

` backend custom503
     mode http
     errorloc303  503 /etc/haproxy/errors/503.http `

To be tested !
