### ISSUE TITLE
Unable to use transparent proxying

### ISSUE THREAD

**Issue by vedit** [mesosphere/marathon-lb#181]
Currently there is no easy way to use transparent proxy for TCP connections. Is it in the roadmap or should I start working on it?

**Comment by brndnmtthws** [comment]
Can you elaborate on what you mean by 'transparent proxy'?

**Comment by brndnmtthws** [comment]
Can you also share the app definition?

**Comment by brndnmtthws** [comment]
Closing this for now. Please feel free to reopen if you have more details.
