### ISSUE TITLE
Support for wildcard vhosts (*.example.com)

### ISSUE THREAD

**Issue by lingmann** [mesosphere/marathon-lb#188]
Currently, it is not possible to configure marathon-lb with wildcard vhosts. This should be possible with haproxy, but we'd have to be careful since ordering would become significant in the rendered haproxy config.

@brndnmtthws is there any chance this is already on your feature roadmap? :) cc: @lloesche

**Comment by brndnmtthws** [comment]
It's come up before (see #161), which I pushed back on. I'm not opposed to making it a 1st class feature, although I feel like we have some serious label proliferation. I'm open to hearing feedback if you feel strongly about this.

**Comment by brndnmtthws** [comment]
By the way, you can change the ACL ordering with `HAPROXY_{n}_BACKEND_WEIGHT`. If you set it to `-1` it'd make sure the rule is at the bottom.

**Comment by lingmann** [comment]
@brndnmtthws hmmm thanks. I don't see it as a critical feature, and there is definitely something to be said for keeping our label variations manageable. For now, I think we'll try and enter all vhosts directly or use the `HAPROXY_{n}_BACKEND_WEIGHT`. @lloesche does this work for you?

**Comment by lloesche** [comment]
The weight would only make sense in combination with `hdr_end(host)` for this use case. I think we're better of avoiding wildcard hostnames altogether. Maybe we can make the matching method configurable in the template. Default it to hdr but allow folks to choose between hdr, _beg, _dir, _dom, _end, _len, _reg, _sub, ...

**Comment by brndnmtthws** [comment]
That seems like a good idea. We could have a separate label like `_VHOST_HDR_MATCH`.

**Comment by micahhausler** [comment]
I got wildcards to work by adding the following lables:
```json
  "labels": {
    "HAPROXY_0_BACKEND_WEIGHT": "-1",
    "HAPROXY_GROUP": "external",
    "HAPROXY_0_HTTP_FRONTEND_ACL": "  acl host_{cleanedUpHostname} hdr_end(host) -i {hostname}\n  use_backend {backend} if host_{cleanedUpHostname}",
    "HAPROXY_0_HTTPS_FRONTEND_ACL": "  use_backend {backend} if {{ ssl_fc_sni -m end .{hostname} }}",
    "HAPROXY_0_VHOST": "example.com"
  }

```

**Comment by brndnmtthws** [comment]
Cool! Want to add that to the wiki?

**Comment by micahhausler** [comment]
@brndnmtthws done

**Comment by scastillo** [comment]
Excuse me guys, but this issue should be consider closed right?
