### ISSUE TITLE
haproxy configuration is not always updated after a marathon task deployment

### ISSUE THREAD

**Issue by moricard** [mesosphere/marathon-lb#194]
I am seeing some strange behaviour that does not happen consistently.

When I update the configuration of a marathon task belonging to the marathon-lb group, sometimes marathon-lb will not update the haproxy configuration to point to the newly deployed task, resulting in failing health-checks and 503s.

This behaviour si not systematic. I run multiple marathon-lb instances on separate machines and usually only one out of 2 will fail to update it's configuration.

I run marathon-lb as a marathon task using the docker image with sse. 

Here is a part of the logs last seen in the faulty marathon-lb container:

```
Configuration file is valid
ok: run: /marathon-lb/service/haproxy: (pid 17) 162498s
Reloading haproxy
[WARNING] 136/122355 (32519) : parsing [/marathon-lb/haproxy.cfg:150] : 'timeout client' will be ignored because backend 'aggregator_12001' has no frontend capability
Configuration file is valid
[WARNING] 136/122355 (32528) : parsing [/marathon-lb/haproxy.cfg:150] : 'timeout client' will be ignored because backend 'aggregator_12001' has no frontend capability
[WARNING] 136/122355 (32528) : In backend 'aggregator_12001' (id: 19): server name mismatch: from server state file: 'ip-10-0-2-119_ec2_internal_31226', from running config 'ip-10-0-2-21_ec2_internal_31309'
```

Killing the faulty marathon-lb from marathon does the job but we suffer from potential downtime of some services during the restart. It is also problematic that marathon health checks are all green but that a background service is red in some, but not all, internal load balancers. We have no idea when a marathon-lb instance becomes out-of-sync with the actual tasks.

**Comment by brndnmtthws** [comment]
Those log messages are actually just warnings.

Since SSE does not provide strong delivery guarantee, it's possible to miss messages. There's a hard-coded 5 minute timeout (see https://github.com/mesosphere/marathon-lb/blob/0b3fab1e3f1666872bb1f388a48a82024c7fd766/marathon_lb.py#L1164), but we could make this configurable. If you used a smaller number (like 30 or 60s) then you'd never be 'out of date' for more than 30 or 60s.

**Comment by moricard** [comment]
It does not seem like a simple out-of-sync problem, I added instances of one service and one of the marathon-lb has these logs:

```
marathon_lb: checking config with command: ['haproxy', '-f', '/tmp/tmpqm76_u81', '-c']
[WARNING] 136/152149 (15253) : parsing [/tmp/tmpqm76_u81:150] : 'timeout client' will be ignored because backend 'aggregator_12001' has no frontend capability
marathon_lb: haproxy returned non-zero when checking config
marathon_lb: skipping reload: config not valid
marathon_lb: updating tasks finished, took 0.11264610290527344 seconds
```

and does not reload. Just as I write these lines, this particular instance of the marathon_lb failed with this message:

```
/marathon-lb/run: line 89:    15 Killed                  /marathon-lb/marathon_lb.py --syslog-socket $SYSLOG_SOCKET --haproxy-config /marathon-lb/haproxy.cfg -c "sv reload $HAPROXY_SERVICE" $ARGS "$@"
```

**Comment by brndnmtthws** [comment]
Interesting. Haven't seen that before. Is there any way for you to grab the HAProxy config? (from `/tmp/tmpqm76_u81`, in the example above).

**Comment by moricard** [comment]
Unfortunately, the container was killed before I could copy it and the file does not seem to exist anymore. I have a bunch of other `/tmp/`tmp******` files but not that one

**Comment by moricard** [comment]
I am seeing more of these failures. At least marathon does a good job of restarting them. All of the runs fail with the same error message:

```
/marathon-lb/run: line 89:    16 Killed                  /marathon-lb/marathon_lb.py --syslog-socket $SYSLOG_SOCKET --haproxy-config /marathon-lb/haproxy.cfg -c "sv reload $HAPROXY_SERVICE" $ARGS "$@"
```

On the other hand, I also have a marathon-lb instance exposing the 'external' group that has not failed or restarted for over a month.

**Comment by brndnmtthws** [comment]
Can you see why it's being killed? How much memory are you allocating?

**Comment by moricard** [comment]
From Mesos, the task is Failed. I am allocating 128Mb of memory

**Comment by brndnmtthws** [comment]
I'm going to take a wild guess and say that your task is being OOM killed. You can verify this by checking the logs. On DCOS, we allocate 1GB of memory for MLB by default, and I suggest you allocate no less than that.

**Comment by moricard** [comment]
That might just be the cause, doing a `docker stats` shows a 97% memory usage. I kind of feel stupid right now. Thanks for pointing out a sensible default memory value.

**Comment by brndnmtthws** [comment]
No sweat. Thanks for opening the issue.
