### ISSUE TITLE
Regardless of the parameter settings："HAPROXY_0_MODE":"tcp"

### ISSUE THREAD

**Issue by houht** [mesosphere/marathon-lb#196]
json:
{
  "id": "mysqltest",
  "labels": {
      "HAPROXY_GROUP":"external",
      "HAPROXY_0_MODE":"tcp",
      "HAPROXY_0_VHOST":"test-app.mysql.com"
  },
  "cpus": 1,
  "mem": 128,
  "disk": 100,
  "instances": 2, 
  "constraints":[["hostname", "UNIQUE"]],
  "container": {
    "docker": {
      "image": "mysql:5.6",
      "network": "BRIDGE",
      "privileged": false,
      "portMappings": [
        {
          "containerPort": 3306,
          "hostPort":0 ,
          "protocol": "tcp",
          "servicePort":0 
        }
      ]
    },
    "type": "DOCKER",
    "volumes": []
  },
  "env": {    "MYSQL_ROOT_PASSWORD": "123456"  }
}

nginx conf:

........
 retries                   3
  backlog               10000
  maxconn               10000
  timeout connect          3s
  timeout client          30s
  timeout server          30s
  timeout tunnel        3600s
  timeout http-keep-alive  1s
  timeout http-request    15s
  timeout queue           30s
  timeout tarpit          60s
  option            redispatch
  option            http-server-close
  option            dontlognull
listen stats
  bind 0.0.0.0:9090
  balance
  mode http
  stats enable
  monitor-uri /_haproxy_health_check
  acl getpid path /_haproxy_getpids
  http-request use-service lua.getpids if getpid
  acl getconfig path /_haproxy_getconfig
  http-request use-service lua.getconfig if getconfig

frontend marathon_http_in
  bind *:80
  mode http
  acl host_test-app_mysql_com_mysqltest hdr(host) -i test-app.mysql.com
  use_backend mysqltest_10001 if host_test-app_mysql_com_mysqltest
  acl host_test-app_gkkxd_com_nginxtest hdr(host) -i test-app.gkkxd.com
  use_backend nginxtest_10000 if host_test-app_gkkxd_com_nginxtest

frontend marathon_http_appid_in
  bind *:9091
  mode http
  acl app__mysqltest hdr(x-marathon-app-id) -i /mysqltest
  use_backend mysqltest_10001 if app__mysqltest
  acl app__nginxtest hdr(x-marathon-app-id) -i /nginxtest
  use_backend nginxtest_10000 if app__nginxtest

frontend marathon_https_in
  bind *:443 ssl crt /etc/ssl/cert.pem
  mode http
  use_backend mysqltest_10001 if { ssl_fc_sni test-app.mysql.com }
  use_backend nginxtest_10000 if { ssl_fc_sni test-app.gkkxd.com }

frontend mysqltest_10001
  bind *:10001
  mode http
  use_backend mysqltest_10001

frontend nginxtest_10000
  bind *:10000
  mode http
  use_backend nginxtest_10000

backend mysqltest_10001
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server test47_10_0_2_47_9003 10.0.2.47:9003
  server test48_10_0_2_48_9536 10.0.2.48:9536

backend nginxtest_10000
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server test47_10_0_2_47_9988 10.0.2.47:9988
  server test48_10_0_2_48_9477 10.0.2.48:9477

**Comment by brndnmtthws** [comment]
You have a vhost set, which isn't possible for TCP, therefore it forces HTTP.

**Comment by houht** [comment]
oh,yes .

thank you very much.

**Comment by mastermindg** [comment]
Why is this not possible with vhosts?

**Comment by brndnmtthws** [comment]
@mastermindg which part? Vhosts require HTTP.
