### ISSUE TITLE
Error in blue-green deployment

### ISSUE THREAD

**Issue by roqmoyano** [mesosphere/marathon-lb#202]
Marathon listening in localhost:8080
HAproxy listening in localhost:9090

When executing:

./bluegreen_deploy.py -j docker.json  -m http://localhost:8080 -f -l http://localhost:9090 

I'm getting this error:

### Traceback (most recent call last):
  File "./bluegreen_deploy.py", line 613, in <module>
    if do_bluegreen_deploy(args):
  File "./bluegreen_deploy.py", line 520, in do_bluegreen_deploy
    deploy_marathon_app(args, new_app)
  File "./bluegreen_deploy.py", line 365, in deploy_marathon_app
    response.raise_for_status()
  File "/opt/python3/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error:  for url: http://localhost:8080/v2/apps

**Marathon version:**

 marathon.x86_64 :         1.1.1-1.0.472.el7  

**Python version**
Tested with python2.7 and python3.4

**OS**
Redhat  7

thanks!

**Comment by brndnmtthws** [comment]
Are both of the service ports available? i.e., unallocated? What version/tag of MLB is it?

**Comment by roqmoyano** [comment]
yes those ports are available and running , I'm using the latest mlb version , this is the marathon log in the moment I'm running the bluegreen script

###  INFO [/app-blue]: new app detected (mesosphere.marathon.upgrade.GroupVersioningUtil$:ForkJoinPool-2-worker-13)
May 30 09:45:15 vm marathon[12992]: [2016-05-30 09:45:15,510] WARN Deployment failed for change: 2016-05-30T12:45:15.506Z (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-13)
May 30 09:45:15 vm marathon[12992]: mesosphere.marathon.ValidationFailedException: Validation failed
May 30 09:45:15 vm marathon[12992]: #011at mesosphere.marathon.api.v2.Validation$.validateOrThrow(Validation.scala:18) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:159) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:157) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.util.Try$.apply(Try.scala:192) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.util.Success.map(Try.scala:237) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [marathon:1.1.1]
May 30 09:45:15 vm marathon[12992]: #011at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [marathon:1.1.1]

**Comment by brndnmtthws** [comment]
Are you trying to use groups? Is there a group named `/app-blue`?

**Comment by roqmoyano** [comment]
there is no app-blue created, I have this configuration in json file:

    HAPROXY_GROUP=external
    HAPROXY_DEPLOYMENT_GROUP=app
    HAPROXY_DEPLOYMENT_ALT_PORT=10001

**Comment by brndnmtthws** [comment]
Can you check the `/v2/groups` endpoint to see if there are any groups defined?

**Comment by roqmoyano** [comment]
it was my fault , I had a app previously deployed using curl and I wanted to do a blue green deployment , so I just tried to deploy the same app from scratch using the zdd.py script and now it works
