### ISSUE TITLE
Add zlib support in haproxy for compression offloading

### ISSUE THREAD

**Issue by davoustp** [mesosphere/marathon-lb#204]
When trying to enable compression offloading in marathon-lb by overriding backend template in Marathon application definition, using label such as `"HAPROXY_0_BACKEND_HEAD": "backend {backend}\n  balance {balance}\n  mode {mode}\n  compression algo gzip\n  compression type text/html text/plain text/css application/javascript application/json\n"`, haproxy complains:
`parsing [/tmp/tmpqqvyi1wb:135] : 'compression' : 'gzip' is not a supported algorithm.`

The core reason is that haproxy was not built with zlib support.

This lies in script `build-haproxy.sh`, where adding `USE_ZLIB=1` in the make stanza would do it.

**Comment by brndnmtthws** [comment]
You can try this with the `latest` tag, by the way.

**Comment by davoustp** [comment]
Tried on latest, everything flies. :-)
Many thanks, marathon-lb is a great piece of work in the Mesos / Marathon toolbox.
