### ISSUE TITLE
SSL backend

### ISSUE THREAD

**Issue by deric** [mesosphere/marathon-lb#206]
Is it possible to configure HAProxy to connect to SSL backends?

I've tried following:
```
HAPROXY_0_BACKEND_SERVER_HTTP_HEALTHCHECK_OPTIONS=check ssl inter 70s fall 4
```
but I'm unable to override the defaults.

**Comment by deric** [comment]
Seems like it could be solved by using:
```
HAPROXY_0_BACKEND_SERVER_OPTIONS= server {serverName} {host_ipv4}:{port}{cookieOptions} ssl verify none{healthCheckOptions}{otherOptions}
```
but a new line needs to be inserted at the end. Marathon UI escapes such sequences, thus it needs to be entered in JSON mode as `\n` (upon next edit it gets deleted unless JSON mode is used).

**Comment by brndnmtthws** [comment]
I think the issue is that you need to use `HAPROXY_0_BACKEND_SERVER_TCP_HEALTHCHECK_OPTIONS` rather than `HAPROXY_0_BACKEND_SERVER_HTTP_HEALTHCHECK_OPTIONS`, as your backend is presumably configured as TCP rather than HTTP.

**Comment by brndnmtthws** [comment]
You may also need to override `HAPROXY_0_BACKEND_TCP_HEALTHCHECK_OPTIONS`, as well.
