### ISSUE TITLE
Detect `HAPROXY_GROUP=external` and automatically disable `HAPROXY_FRONTEND_HEAD`

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon-lb#215]
Marathon-LB will offer frontend ports for every service on their service port. While this is normally desired behavior, it's less awesome when using the default `external` group, as when launching on a public slave. In this particular case, we'd like to automatically disable the creation of these frontends to prevent any security-related surprises.

**Comment by brndnmtthws** [comment]
I'm not convinced this requires changes to MLB. To me this sounds like a firewall/security policy issue. Since you might want to still use the same instance of MLB for internal routing, you would simply close those ports to the internet rather than disabling binding altogether.

**Comment by lloesche** [comment]
The behaviour you describe is the desired outcome and can be overridden using `HAPROXY_{n}_FRONTEND_HEAD` on a per service port bases.
The group name `external` is just an arbitrary string. It has no special meaning to marathon-lb. It just happens to be what the Dockerfile uses for the `--group` arg by default. In non-docker installations the default group matches `*`.
Doing this change would break existing marathon-lb installations.

**Comment by jgarcia-mesosphere** [comment]
Good deal, thanks for considering!

**Comment by jgarcia-mesosphere** [comment]
Related wiki page: https://github.com/mesosphere/marathon-lb/wiki#disable-binding-to-service-ports
