### ISSUE TITLE
Change backend name in HAProxy using labels

### ISSUE THREAD

**Issue by maauso** [mesosphere/marathon-lb#219]
Hi, 

We need add differents Marathon tasks under the same back-end in HAProxy, I don't find the way to do it, I think that I need use some label that I can change the back-end name in HAProxy. 

Any idea? this is possible? 

Thanks!

**Comment by brndnmtthws** [comment]
Combining 2 separate apps into one backend isn't currently possible with MLB. Each app is treated separately, and no amount of template finagling will result in a proper config.
