### ISSUE TITLE
Rollback for zdd(blue green deployment)

### ISSUE THREAD

**Issue by ajays20078** [mesosphere/marathon-lb#221]
Currently if the zdd.py  script fails midway, there is no exception handling or rollback, hence it leaves the system in a inconsistent state with few tasks in blue group and few tasks in green group.

**Comment by brndnmtthws** [comment]
Perhaps we could add a `--rollback` flag, which would remove the new app entirely? Currently it's left up to the user to decide how to proceed (i.e., requires manual intervention).

**Comment by ajays20078** [comment]
The script could fail after it has created a few tasks in new group and deleted a few tasks in older group.

So yes, we need to delete new app  and then scale back the old app to its original count, else the app might suffer degradation due to lesser number of instances.

This again is equivalent of new deployment as we are adding tasks to old app group and deleting tasks from new app group. Also whatever caused the initial deployment to fail, might cause the rollback to fail as well. 

Wouldn't supporting something on the lines of `--min-tasks-in-group` , which is minimum number of containers which will be created in new app group before deleting containers from old app group help here? As we can always be sure we will have minimum number in both the groups, so we can go ahead and delete either one, based on user flag, as both have the required capacity.

**Comment by brndnmtthws** [comment]
I think we could just scale to the target number of instances (which is set as a label).

**Comment by ajays20078** [comment]
This is fixed with the new hybrid Blue-Green ( #250  ) deployment since it supports rollback with `--complete-prev` flag. 

Also for deployments which are not hybrid , we can ensure the apps are not degraded by setting `--initial-instances` of new version to be same as number of existing instances of current version, that ensures we have full capacity of either one of the versions even if deployment fails midway.
