### ISSUE TITLE
static vhost

### ISSUE THREAD

**Issue by JaSei** [mesosphere/marathon-lb#222]
Hi, I liked marathon-lb - is it realy cool tool. I used to consul+mesos-consul-bridge+consul-template+lighttpd, but now migrate our cluster to marathon-lb.

I have question: is possible create _static vhost_ - means. vhost which doesn't in marathon (aka marathon.my_cloud -> my_cloud:8080 for example)?

thanks

**Comment by JaSei** [comment]
My idea is on each master run mesos-master, marathon and marathon-lb.

I do template `templates/HAPROXY_HTTP_FRONTEND_HEAD`:
```
backend marathon_8080
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server local localhost:8080

backend mesos_5050
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server local localhost:5050


frontend marathon_http_in
  bind *:80
  mode http

  acl marathon hdr(host) -i marathon.my_cloud
  use_backend marathon_8080 if marathon
  acl mesos hdr(host) -i mesos.my_cloud
  use_backend mesos_5050 if mesos
```

and then
`docker run --rm -v $PWD/templates:/marathon-lb/templates -e PORTS=9090 --net=host --privileged=true mesosphere/marathon-lb:v1.2.2 sse --marathon http://localhost:8080 --group internal`

this is work... exists some better way?
thanks

**Comment by brndnmtthws** [comment]
Yep, you can do that. This isn't really how MLB was meant to be used, but it's possible. As an alternative, I'd suggest you just run a second instance of HAProxy or nginx on Marathon pointing to your backend, and configure that the normal way through MLB.
