### ISSUE TITLE
set HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS has a bug

### ISSUE THREAD

**Issue by zhengqisong** [mesosphere/marathon-lb#224]
I use marathon to create app, set labels is {"HAPROXY_0_BACKEND_REDIRECT_HTTP_TO_HTTPS":"true"}, but could not be written to the haproxy configuration file.
I find is a bug.
"marathon_lb.py" in 1086 lines:
            func(service,
               key_unformatted,
               marathon_app.app['labels'][key])

config.py in 1027 lines:
    def string_to_bool(s):
       return s.lower() in ["true", "t", "yes", "y"]

The function definition and call contradiction,should be changed as follows:
    def string_to_bool(s, k, v):
       if v.lower() in ["true", "t", "yes", "y"]:
          s[k] = True
       else:
          s[k] = False

**Comment by brndnmtthws** [comment]
Thanks! Could you create a PR with this change?

**Comment by jkoelker** [comment]
I'm unable to replicate this with the following config, so I believe it may have been fixed in the past few releases. Please let me know if this is still and issue.

```json
{
  "id": "/nginx",
  "labels": {
      "HAPROXY_GROUP": "external",
      "HAPROXY_0_VHOST": "test.exmplae.com",
      "HAPROXY_0_BACKEND_REDIRECT_HTTP_TO_HTTPS": "true"
  },
  "container": {
    "portMappings": [ {
        "containerPort": 80,
        "protocol": "tcp",
        "name": "web"
      }],
    "type": "MESOS",
    "docker": {"image": "nginx"}
  },
  "healthChecks": [
    {
      "portIndex": 0,
      "path": "/",
      "protocol": "HTTP"
    }
  ],
  "cpus": 0.1,
  "instances": 1,
  "mem": 128,
  "networks": [{"mode": "container/bridge"}]
}
```
