### ISSUE TITLE
No marathon_http_in section generated on internal group

### ISSUE THREAD

**Issue by ensonik** [mesosphere/marathon-lb#226]
For the life of me, I can't get a vhost to register on my internal marathon-lb group. No problems on the external one though ...

Is the internal group treated differently than external?

More info:
- the haproxy.cfg file generated doesn't contain a marathon_http_in section (the external one does)
- Obviously, I do have a HAPROXY_0_VHOST label in my marathon deployment.
- When tailing the logs, it seems to want to do something: `marathon_lb: adding virtual host for app with id /myapp`

Thanks for any insight.

**Comment by brndnmtthws** [comment]
This is intentional. By specifying the `--dont-bind-http-https` option, we disable the HTTP and HTTPS frontends. See https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#command-line-usage for reference.
