### ISSUE TITLE
Help Getting the Real Requesting IP Address

### ISSUE THREAD

**Issue by christopherhein** [mesosphere/marathon-lb#227]
I've been trying to figure out the proper configuration setup for my marathon app running on dcos. I'm using marathon lb on my public nodes all fed from an ELB. It seems with the default configurations when I grab the `X-Forwarded-For` header I'm actually getting the IP address from the ELB. 

Has anyone had experience with this, if so could you share your config?

**Comment by brndnmtthws** [comment]
There should actually be 2 separate `X-Forwarded-For` headers. Try this: http://requestheaders.diddyinc.com/

**Comment by paambaati** [comment]
@brndnmtthws The URL throws a `ERR_NAME_NOT_RESOLVED` error. Would you mind posting the solution, or the updated URL?

**Comment by brndnmtthws** [comment]
@paambaati here's the source you can run it for yourself: https://github.com/brndnmtthws/nginx-echo-headers
