### ISSUE TITLE
It could happen that, in event mode, our subscription is lost and we are never called back

### ISSUE THREAD

**Issue by valentinomiazzo** [mesosphere/marathon-lb#230]
This happened during a network split where some slaves reconnected multiple time with the master.
We found that after the network issue the cluster was still unstable.
This was due to marathon-lb not updating the haproxy config.
This commit on a fork contains a possible fix: marathon-lb periodically re-subscribes.

https://github.com/valentinomiazzo/marathon-lb/commit/835d500b4f7cc4f2582b9c425e49e048aa89cf2f

**Comment by brndnmtthws** [comment]
Can you elaborate on the problem? Do you have logs from MLB?

**Comment by valentinomiazzo** [comment]
I'm sorry but I don't have meaningful logs.

I can try to restate what happened.
We had a network split where the 3 masters and 3 clients remained connected.
The other 5 clients where not reachable form the master and vice versa.
During the network split the 5 clients joined the cluster multiple times (at least 3 times) following the up and downs of the network.
At a certain point the network became stable and all the clients where stable in the cluster.
Anyway, the services where not healthy and Marathon seemed to randomly restart services.
After a while we discovered that one of the clients had a outdated haproxy.cfg.
We restarted the marathon-lb services on all the clients and this solved the issue, the cluster was stable again.

I suspect that during the network split:
- the master 'forgot' subscriptions for clients that disappeared from the cluster
- when the clients rejoined, marathon-lb didn't receive callbacks from masters and
- didn't update haproxy.cfg

Looking at the code, it seems MLB subscribes to masters only at the start.
If for whatever reason, the subscription is lost, then MLB is never called back and haproxy not updated.

It could be useful to re-subscribe periodically to work around such situations.
The fork is an example of what I mean.

Thanks,
Valentino

**Comment by brndnmtthws** [comment]
So you're using the `event` mode, as opposed to SSE?

**Comment by brndnmtthws** [comment]
Please test the `mesosphere/marathon-lb:set-socket-timeout` image and let me know if that helps.

**Comment by valentinomiazzo** [comment]
I'm reading https://github.com/mesosphere/marathon-lb#operational-best-practices and it occurred to me that we are not using MLB in the standard way.

We have one instance of MLB and HAproxy for each Mesos slave. 
A client that is not running in Mesos will connect directly to one of the slaves through a round robin DNS containing slaves IPs (we are ready to replace it with a real balancer).
A client running in Mesos that want to talk to another service in Mesos connects using localhost, here HAproxy will proxy it to the right IP/port.

The advantage of this setup, we think, is that if client and service are running on the same node then the communication will remain local to the node.
It also spread the network traffic across more nodes and avoid the LB hop.
About hammering, the 3 masters currently have very low CPU and network usage.

The MLB running on each slave are configured to work in Event mode.
```
marathon_lb.py --marathon http://public_ip_of_master0:8080 --marathon http://public_ip_of_master1:8080 --marathon http://public_ip_of_master2:8080 --group '*' --listening http://this_slave_private_ip:8080 --callback-url http://this_slave_private_ip:8080 --ssl-certs /etc/ssl/my.pem
```

Do you suggest to switch to SSE mode?
What do you think about our setup? Is it sensible or a big no no?
About testing it, it is hard to replicate the network split so I don't think we'll have data for you any time soon.

**Comment by brndnmtthws** [comment]
SSE is preferred, and I'll probably remove the subscription method at some
point exactly for the reason you've described.

**Comment by valentinomiazzo** [comment]
Thanks, for the feedback.
We'll try the branch.
