### ISSUE TITLE
Port information should be extracted from App#portDefinitions

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon-lb#231]
The`AppDefinition#ports` field is deprecated. The port information should be extracted from `App#portDefinitions` instead.

**Comment by brndnmtthws** [comment]
Is the behaviour otherwise the same? It's not clear to me whether or not this change will break existing features.

**Comment by gkleiman** [comment]
Yes, the behaviour is otherwise the same, and we're considering removing the deprecated`AppDefinition#ports` field in future releases.

cc/ @jdef

**Comment by brndnmtthws** [comment]
Okay, PR'd.
