### ISSUE TITLE
docs: please indicate which templates apply to public/internal

### ISSUE THREAD

**Issue by jdoklovic** [mesosphere/marathon-lb#233]
When trying to apply service level templates via labels in the marathon descriptor, I realized deploying to public vs. internal changes which templates/labels are valid for the given environment.

Unfortunately the template docs do not specify which templates are valid for which environment so there's a lot of trial/error and dumping of the haproxy config to figure out exactly which templates to use.

Please add a lozenge or something to each template in the docs specifying if it's public, internal, or both.

**Comment by brndnmtthws** [comment]
I don't fully understand your question. Are you referring to the case where you're running multiple LBs, one of which is internal, the other of which is public?

If that's the case, all labels apply to all LBs where the `HAPROXY_GROUP` label matches the LB's group.
