### ISSUE TITLE
Invalid HAProxy config causes marathon-lb to stop trying

### ISSUE THREAD

**Issue by nghgd** [mesosphere/marathon-lb#234]
The main problem here is that, if a user sets up options improperly to cause an haproxy configuration error, even after correcting the issue which causes the haproxy config to have a fatal error, marathon-lb will be stuck and not receive new updates and marathon-lb must be restarted to resolve the issue.

I am using SSE mode.

The following are the last log entries from the container:

```
marathon_lb: reading running config from /marathon-lb/haproxy.cfg
marathon_lb: running config is different from generated config - reloading
marathon_lb: writing config to temp file /tmp/tmp95z_ycw9
marathon_lb: skipping validation. moving temp file /tmp/tmp95z_ycw9 to /marathon-lb/haproxy.cfg
marathon_lb: reloading using sv reload /marathon-lb/service/haproxy
ok: run: /marathon-lb/service/haproxy: (pid 15) 606605s
Reloading haproxy
[ALERT] 174/171924 (7841) : parsing [/marathon-lb/haproxy.cfg:83] : 'option httpchk' cannot handle unexpected argument 'timeout'.
[ALERT] 174/171924 (7841) : Error(s) found in configuration file : /marathon-lb/haproxy.cfg
[ALERT] 174/171924 (7841) : Fatal errors found in configuration.
Invalid config
marathon_lb: received event of type status_update_event
```

After this point, marathon-lb will no longer attempt to pull new config due to marathon changes.

**Comment by brndnmtthws** [comment]
Indeed, if the config is invalid, it will fail. There isn't much I can do about this, except implore that you carefully test changes before deploying them.

**Comment by nghgd** [comment]
Failing isn't the problem, the problem is that marathon-lb is "dead" and unable to receive any new updates until the container is restarted. Even if someone corrects the issue so that valid config would be generated, it's stuck until the container is restarted.

**Comment by brndnmtthws** [comment]
Yes, that's correct. If you start MLB with an invalid config, HAProxy will never start.

**Comment by nghgd** [comment]
This is the series of events:

1. Marathon-lb is running fine and has the correct configuration
2. User inputs a bad option through the Marathon UI
3. Marathon-lb tries to reload haproxy, and fails
4. User corrects the option
5. Marathon-lb no longer receives updates to correct itself
6. User must restart marathon-lb to retrieve new marathon configuration
7. Marathon-lb starts HA Proxy fine because config is correct

**Comment by brndnmtthws** [comment]
I just ran a test as you described, and everything seemed to work as expected (i.e., when I fixed the busted label, everything was fine).

What version of MLB are you running? Can you provide any more details such as logs?

**Comment by nghgd** [comment]
Using 1.2.2.

I use this command to start marathon-lb:
```
docker run -d --name "slave-lb-{{ grains['id'] }}" --restart always -p 80:80 -p 443:443 -p 9090:9090 -e "PORTS=80,443,9090" --privileged=true --volume=/data/marathon-lb/templates:/marathon-lb/templates mesosphere/marathon-lb:v1.2.2 sse --marathon http://marathon.{{ pillar['domain'] }} --skip-validation --group external --health-check
```

I broke things accidentally by using the marathon ui to enter data instead of json, copying/pasting from marathon stripped out \n which resulted in the following which I entered in another label:
```
"HAPROXY_0_BACKEND_HTTP_HEALTHCHECK_OPTIONS": "  option  httpchk GET {healthCheckPath} HTTP/1.1\\r\\nHost:\\ test.com  timeout check {healthCheckTimeoutSeconds}s",
```

This resulted in the timeout line and first server line being put on the option httpchk line.

The logs I pasted in the first message is where the MLB halted; everything up until then was basically normal, until it tried to reload with this bad config. After that point, no new logs were created even after changing Marathon config multiple times (this same thing happened on all 3 MLB instances I have; after fixing the issue and also restarting MLB, things finally worked again). If further logs would be desired I can cause this again (I actually believe I've triggered this a few times recently working with MLB, I just didn't realize this was the cause of why MLB stopped receiving updates until now), just let me know.

**Comment by brndnmtthws** [comment]
Okay, I'll reopen this and investigate when I get a chance.

**Comment by nghgd** [comment]
Thanks!

**Comment by brndnmtthws** [comment]
Maybe the same issue as #230, although I've still not reproduced this.

**Comment by brndnmtthws** [comment]
Please test the `mesosphere/marathon-lb:set-socket-timeout` image and let me know if that helps.

**Comment by nghgd** [comment]
Been pretty busy with stuff the last couple of days and will be the next few days, but I will test this as soon as I can and report back, thank you!

**Comment by brndnmtthws** [comment]
I'm going to close this under the assumption that #240 resolves it. Please reopen if it happens again.
