### ISSUE TITLE
monitor sse mode

### ISSUE THREAD

**Issue by MikeMichel** [mesosphere/marathon-lb#238]
i just ran into the following isue:  even with using health checks the rolling deployment took very long and we saw 503 errors for the app because marathon-lb was not updated in time. after a while i found out that sse stopped working at all and the haproxy.cfg was only updated because of the 5 minute fallback option. 

after a restart of the marathon-lb container everything is updated immediately again. question is now how to monitor sse connection so i am aware of the delayed update which causes downtime of our apps when redeployed.

**Comment by brndnmtthws** [comment]
Please test the `mesosphere/marathon-lb:set-socket-timeout` image and let me know if that helps.

**Comment by brndnmtthws** [comment]
I'm going to close this under the assumption that #240 resolves it. Please reopen if it happens again.

**Comment by MikeMichel** [comment]
thanks i will test it
