### ISSUE TITLE
ip-per-container suspended app error

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon-lb#242]
> Auto assigning service port for IP-per-container task
> marathon_lb: Unexpected error!
> Traceback (most recent call last):
>   File "/marathon-lb/marathon_lb.py", line 1334, in do_reset
>     self.__apps = get_apps(self.__marathon)
>   File "/marathon-lb/marathon_lb.py", line 1216, in get_apps
>     service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
>   File "/marathon-lb/utils.py", line 122, in get_service_ports
>     task = app['tasks'][0]
> IndexError: list index out of range

**Comment by brndnmtthws** [comment]
cc @robbrockbank

**Comment by brndnmtthws** [comment]
Go ahead and test `mesosphere/marathon-lb:fix-0-instance-bug`

**Comment by vixns** [comment]
tested and working, thanks.

While testing, after updating and resetting  a mesos agent, there was several old tasks stalled, dead but still present in zookeeper, cleaning zookeeper and restart marathon fixed this.

This seems like a local or marathon issue, however marathon-lb should always ignore invalid tasks.

```
Auto assigning service port for IP-per-container task
Task internal_registry_registry.4d5eba6f-3dd9-11e6-b97b-c6891ad39202 does not yet have an ip address allocated
marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1337, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1219, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 125, in get_service_ports
    for task_port in task_ports]
TypeError: 'NoneType' object is not iterable
```

**Comment by brndnmtthws** [comment]
Weird. Here's another PR: https://github.com/mesosphere/marathon-lb/pull/253
