### ISSUE TITLE
HAPROXY_{n}_AUTH not working

### ISSUE THREAD

**Issue by robsonpeixoto** [mesosphere/marathon-lb#244]
When I use the `HAPROXY_{n}_AUTH` it ask for the password but the user/password never work and keep asking forever.

```json
{
  "id": "/basic-3",
  "cmd": "python3 -m http.server 8080",
  "cpus": 0.5,
  "mem": 32,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "python:3",
      "network": "BRIDGE"
    }
  },
  "labels": {
    "HAPROXY_0_VHOST": "basic-3.my.domain",
    "HAPROXY_GROUP": "external",
    "HAPROXY_0_AUTH": "basic-3:user:pass"
  }
}
```

**Comment by brndnmtthws** [comment]
Did you follow the instructions? https://github.com/mesosphere/marathon-lb/wiki/HTTP-Basic-Auth

**Comment by robsonpeixoto** [comment]
No @brndnmtthws. Just a suggestion, add a link here https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_n_auth

**Comment by brndnmtthws** [comment]
Yep, I just added it. Thanks for opening the issue!

**Comment by robsonpeixoto** [comment]
The current version are not beauty. 
![image](https://cloud.githubusercontent.com/assets/124390/16456965/3fda5f02-3df0-11e6-9eba-1f2ab5221877.png)

I made this small change https://github.com/mesosphere/marathon-lb/pull/245

**Comment by robsonpeixoto** [comment]
I'm having problem with auth, again. I can't figure out why, because it's working for some apps, but for others are not working =/

```json
{
  "id": "/ted/basic-1",
  "args": [
    "python", "-m", "http.server", "8080"
  ],
  "cpus": 0.5,
  "mem": 32.0,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "python:3",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 8080, "hostPort": 0 }
      ]
    },
    "healthChecks": [
      {
        "protocol": "HTTP",
        "path": "/",
        "portIndex": 0,
        "gracePeriodSeconds": 30,
        "intervalSeconds": 1,
        "timeoutSeconds": 1,
        "maxConsecutiveFailures": 3
      }
    ]
  },
  "labels": {
    "HAPROXY_GROUP": "internal",
    "HAPROXY_0_VHOST": "basic-1.my.domain",
    "HAPROXY_0_AUTH": "realm:username:$1$dHq4rH9P$SXKbaqWIodmCSHz6DzvHp."
  }
}
```

The `HAPROXY_0_AUTH` are exactly the same from the documentation.

When I activate the auth, all requisition I get a `503 Service Unavailable`  but when I remove it works well.

Any idea ?

**Comment by brndnmtthws** [comment]
Can you share the generated HAProxy config?

**Comment by pdiniz13** [comment]
I am getting the same error. I followed the instructions, but as soon as I turn on auth I get a 503.

**Comment by robsonpeixoto** [comment]
I have no idea what's happen. I tried now to attach the haproxy config file and the auth are working well =/

**Comment by pdiniz13** [comment]
Sorry can u attach the config anyways so I can compare with mine.
