### ISSUE TITLE
Mesos 1.6 HTTPS Vhost getting 502 bade gateway

### ISSUE THREAD

**Issue by udaraliyanage** [mesosphere/marathon-lb#246]
I am able to add a Vhost to Marathonlb and access it via marathonlb when the backend service is http. But when the backend service is https, I am always getting 502 Bad Gateway when accessed via marathonlb. I did n't provide any certs since doc [1] says it generate a self signed certificate.
Do we have to configure anything other than HAPROXY_0_VHOST when the backend service is an https one?

[1] https://mesosphere.com/blog/2015/12/13/service-discovery-and-load-balancing-with-dcos-and-marathon-lb-part-2/

**Comment by brndnmtthws** [comment]
If it works via HTTP, it'll work through HTTPS. Try reading this: http://mesosphere.com/blog/2016/04/06/lets-encrypt-dcos/

**Comment by vanomashey** [comment]
Hi Udara, could you share the solution you found?
