### ISSUE TITLE
nginx return "503 Service Unavailable" with about 50% probability

### ISSUE THREAD

**Issue by kiwenlau** [mesosphere/marathon-lb#247]
I want to deploy nginx using Mesos/Marathon platform, using marathon-lb for service discovery and load balance:

Following is the JSON definition of nginx:

```
{
    "id": "nginx",
    "labels": {
        "HAPROXY_GROUP": "external"
    },
    "cpus": 0.2,
    "mem": 20.0,
    "instances": 2,
    "healthChecks": [{
        "path": "/"
    }],
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "nginx",
            "network": "BRIDGE",
            "portMappings": [{ "containerPort": 80, "hostPort": 0, "servicePort": 80, "protocol": "tcp" }]
        }
    }
}
```

It seems that nginx works well, but sometimes it will return "503 Service Unavailable":

```
curl 192.168.59.1:80
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
 
So I write a shell script to calculate the probability of returning "503 Service Unavailable", it turns out that the probability is about **50%**, I'm quite surprise about it...

There may be some problem related to marathon-lb, I use 1.3.0

**Comment by brndnmtthws** [comment]
Binding directly to port 80 isn't going to work. Read the documentation or blog posts on how to use a vhost.

https://mesosphere.com/blog/2015/12/04/dcos-marathon-lb/
https://mesosphere.com/blog/2015/12/13/service-discovery-and-load-balancing-with-dcos-and-marathon-lb-part-2/
https://github.com/mesosphere/marathon-lb#app-labels

**Comment by kiwenlau** [comment]
Problem solved by just changing service port from 80 to 10000, nginx is 100% available now.

However, I can not understand the reason....
