### ISSUE TITLE
Statsd or collectd metrics?

### ISSUE THREAD

**Issue by ryankennedyio** [mesosphere/marathon-lb#248]
Hi,

We've recently set up a graphite & grafana install for tracking the usual metrics. I'm wondering if there are any suggested best practices for including marathon-lb in our metrics?

We handle all response codes in our application layer behind Marathon-lb, but we'd really like to know about the times where marathon returns a 503, or times out because we need more instances running, or similar. Essentially every time a request is sent to us, but isn't handled by our application code, we'd love to know about it.

We're using the bobrik/collectd-docker container on each host within our mesos cluster, if that's any help. Sends all data to a graphite database, with Grafana sitting on top.

**Comment by arkan** [comment]
Hi,
My services are also load balanced with marathon-lb. I'm using Datadog to get information about response time, traffic, status codes, and so on ... 
The code used to report this is available here if you want to see what it looks like: https://github.com/DataDog/dd-agent/blob/master/checks.d/haproxy.py

**Comment by ryankennedyio** [comment]
Ah cool, that looks like a great starting point. I'm not familiar with DataDog -- how do you set that agent up alongside marathon-lb?

**Comment by arkan** [comment]
Basically I have this https://github.com/DataDog/docker-dd-agent running on each instance. 

You can find an example of how I use it here: https://gist.github.com/arkan/7937526c9349655a1f2a326293a8628d

This way, I can easily have Haproxy metrics reported to Datadog ❤️

**Comment by ryankennedyio** [comment]
Thanks @arkan  -- appreciate it a lot.
