### ISSUE TITLE
marathon-lb removing Host request-header field

### ISSUE THREAD

**Issue by whiplash** [mesosphere/marathon-lb#251]
It looks like marathon-lb currently removes Host request-header field.

I'm totally new to haproxy, so I might be wrong, but my services currently requires Host field to be present.

Currently when I check `_haproxy_getconfig` I get something like this:

```
backend foobar_http_35164
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  option  httpchk GET /
  timeout check 20s
  server SOMESERVER SOMESERVER:8249 check inter 60s fall 4
```

Am I doing something wrong?

**Comment by brndnmtthws** [comment]
Hmm, HAProxy shouldn't be removing any headers. How are you testing it?

**Comment by whiplash** [comment]
I'm deploying a service written using [akka-http](http://doc.akka.io/docs/akka/2.4.7/scala/http/configuration.html) and and its log is full of
`Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header: Cannot establish effective URI of request to `/`, request has a relative URI and is missing a `Host` header`.

Luckily akka-http has this `default-host-header` property that you can put in cases where there is none.

Still I was curious to know why this was happening.

**Comment by brndnmtthws** [comment]
I haven't seen it before. In fact, I run a couple test sites which return the HTTP headers when you make a request:

https://ssl-test-1.mesosphere.com/
https://ssl-test-2.mesosphere.com/

You can see the host header above.

**Comment by brndnmtthws** [comment]
I made this to test:

http://requestheaders.diddyinc.com/

Source:

https://github.com/brndnmtthws/nginx-echo-headers

Everything looks a-okay to me.

**Comment by whiplash** [comment]
What's your haproxy conf though?
Also, a little detail I should add, it looked like HOST header was missing only during healthchecks.

Anyways, I'll try and replicate this and let you know.

Thanks.

**Comment by brndnmtthws** [comment]
Ah, that's a known issue. If you need it for health checks, try this: https://github.com/mesosphere/marathon-lb/wiki#custom-http-headers-in-health-check

**Comment by whiplash** [comment]
I need it for everything (and as far as I know it's a required header field).
Yeah, we're doing that now. I did not know it's a a known issue. Is it a haproxy known issue? Could you link me somewhere I can read about this known issue?

**Comment by brndnmtthws** [comment]
This is just how HAProxy normally does it. HAProxy can't possibly know what host header to pass unless you specify it.

**Comment by whiplash** [comment]
Makes sense. Thanks.

**Comment by paambaati** [comment]
@brndnmtthws I tried setting the label (via Marathon UI), but the HAProxy config validation fails.

The generated temp file has this line —

```
option  httpchk GET / HTTP/1.1\\r\\nHost:\\ www\n  timeout check 10s\n  server x_x_x_x_port x.x.x.x:<port> check inter 20s fall 4
```

When ideally it should look like this —

```
option  httpchk GET / HTTP/1.1\r\nHost:\ www
timeout check 10s
server x_x_x_x_port x.x.x.x:<port> check inter 20s fall 4
```

Are the slashes not escaped correctly?

**Comment by brndnmtthws** [comment]
@paambaati looks like your newlines are being doubly-escaped, maybe a bug in the UI. Try updating the labels via the REST API.

**Comment by paambaati** [comment]
@brndnmtthws Yup, can confirm that the UI is at fault here. The REST API works fine.
