### ISSUE TITLE
SSL config returning 503 or failure for python clients depending on OPENSSL_VERSION

### ISSUE THREAD

**Issue by ryankennedyio** [mesosphere/marathon-lb#254]
Hi,

Unsure if this is a configuration issue that can be solved within Marathon UI.

Our SSL certificates were working perfectly with an NGINX proxy -- the only difference I can think of between the two is that `marathon-lb` uses a concatenated key + crt into .pem. The base server of Marathon-LB is Debian Stretch, and our previous NGINX proxies were from an Ubuntu base image.

For reference, Python clients using a few different versions of OPENSSL will return different results. In order of descending dates for openssl;

#### Python 2.7.11 with OpenSSL 1.0.2h  3 May 2016
Will return `200`

#### Python 3.5.1 with OpenSSL 1.0.2g  1 Mar 2016
Will return `200`

#### Python 2.7.10 with OpenSSL 0.9.8zh 14 Jan 2016
`SSLError: EOF occurred in violation of protocol (_ssl.c:590)`

#### Python 3.5.1 with OpenSSL 0.9.8zh 14 Jan 2016
`ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)`

#### Python 2.7.6 with OpenSSL 1.0.1f 6 Jan 2014
Will return `503`

These should all be returning `200`, and are when using NGINX proxy.

**Comment by brndnmtthws** [comment]
Older versions of SSL/TLS have been disabled by default, but you may re-enable them if you choose: https://github.com/mesosphere/marathon-lb/wiki#enabling-tls-v10

**Comment by ryankennedyio** [comment]
Thank you @brndnmtthws
