### ISSUE TITLE
Fronting an application using HOST network mode with Marathon-LB does not work

### ISSUE THREAD

**Issue by isurulucky** [mesosphere/marathon-lb#255]
Hi,

I have a application [1], which is using HOST network. I would like to expose some of the port via the marathon load balancer. Added the HAPROXY_GROUP, but seems the haproxy is not picking up the application. Any idea on what is happening here?

[1].
{
"id": "xxxx",
"cpus": 0.5,
"mem": 1024.0,
"instances": 1,
"executor": "",
"container": {
"type": "DOCKER",
"docker": {
"image": "xxxx:1.0.0",
"network": "HOST",
"portMappings": [
{
"protocol": "tcp",
"containerPort": 4000,
"servicePort": 10060,
"hostPort": 4000
},
{
"protocol": "tcp",
"containerPort": 11224,
"servicePort": 10176,
"hostPort": 11224
}
]
}
},
"portDefinitions": [
{
"port": 4000,
"protocol": "tcp"
},
{
"port": 11224,
"protocol": "tcp"
}
],
"requirePorts": true,
"healthChecks": [
{
"portIndex": 1
}
],
"labels": {
"HAPROXY_GROUP": "marathon-lb"
}
}

**Comment by brndnmtthws** [comment]
It works just fine.

Please read through the guides which cover this:

https://mesosphere.com/blog/2015/12/04/dcos-marathon-lb/
https://mesosphere.com/blog/2015/12/13/service-discovery-and-load-balancing-with-dcos-and-marathon-lb-part-2/

**Comment by brndnmtthws** [comment]
By the way, I'd remove those portmappings, as they mean nothing in host networking mode. Your app should be listening on ports 4000 and 11224, as per your app definition.

**Comment by brndnmtthws** [comment]
Also check that your `HAPROXY_GROUP` actually matches what you have set on MLB. The default on DC/OS is `external`.
