### ISSUE TITLE
How to configure https with VHOST?

### ISSUE THREAD

**Issue by vanomashey** [mesosphere/marathon-lb#260]
Hi Guys,
I did managed to configure marathonlb for http requests. I cannot configure it for my project using https and path. Basically the service is running in marathon using ssl as well. I cannot see what kind of parameters do I need to set to get it running. 
I have added HAPROXY_0_REDIRECT_TO_HTTPS =true, HAPROXY_0_SSL_CERT =path, HAPROXY_0_PATH and HAPROXY_0_VHOST=https://... I assume It is not correct to add https in the VHOST. But if not there, then where? 
I would appreciate any pointer. Thank you.

**Comment by brndnmtthws** [comment]
Here's a guide on using HTTPS with MLB: https://mesosphere.com/blog/2016/04/06/lets-encrypt-dcos/

You don't need to use the Let's Encrypt part, but it should cover the rest of what you need for enabling HTTPS.

**Comment by vanomashey** [comment]
Hi Brenden,
Thank you for the quick reply. 

The example you list is unclear. 
1) Path is specified in Marathon LB app and not in the apps. In my opinion, Path is the part of URL of the app.
2) Vhosts are listed for the Marathon LB . We have dynamic cluster and have different amount of apps everyday. Can we use wildcards there?
3)  it is still not clear to me how Marathon LB knows if reverse proxy should be configured to https or http. There is no difference in configs for http and https apps. Can you clarify on this?

Overall we were looking for this feature very long, but unfortunately documentation is lacking details. I really appreciate your help.

Regards,
Ivan

**Comment by brndnmtthws** [comment]
I don't understand your questions, but I'll try to address each point:

> 1) Path is specified in Marathon LB app and not in the apps. In my opinion, Path is the part of URL of the app.

Are you referring to routing by path? This is specified as an app label.

> 2) Vhosts are listed for the Marathon LB . We have dynamic cluster and have different amount of apps everyday. Can we use wildcards there?

Here's an example of vhost wildcards: https://github.com/mesosphere/marathon-lb/wiki#wildcard-vhosts-resolution

> 3) it is still not clear to me how Marathon LB knows if reverse proxy should be configured to https or http. There is no difference in configs for http and https apps. Can you clarify on this?

MLB listens on ports 80 (HTTP) and 443 (HTTPS) by default. Apps with a vhost set will be available on both 80 and 443.

Like I said before, you should read through the entire guide which covers most of these usage questions.
