### ISSUE TITLE
override HAProxy template

### ISSUE THREAD

**Issue by erikrs** [mesosphere/marathon-lb#264]
i need help on how to override HAProxy (marathon-lb) templates; 
i try to follow example in marathon-lb docs "overridable templates" but it doesn't override it. My example is this: 

`"HAPROXY_0_HTTP_BACKEND_PROXYPASS": "  http-request set-header Host {hostname}\\n  reqirep  ^([^\\ :]*)\\ (.*) \\1\\ /test\\2",`

resulting in actual HAProxy config (via host:9090/_haproxy_getconfig): 

`reqirep  "^([^ :]*)\   http-request set-header Host {hostname}\n  reqirep  ^([^\ :]*)\ (.​*) \1\ /test\2(.*​)" "\1\ /\2"`

which is actually the default template filled in with my values (I also tried to specify "HAPROXY_HTTP_BACKEND_PROXYPASS" label, without 0)

Purpose is to configure marathon-lb (HAProxy) to route to backend to a path on a vhost (ie. incoming: example.com; backend: 10.0.0.1:1234/test/) ? thx !

**Comment by brndnmtthws** [comment]
There's a bug here, and it looks like it's actually broken. I'll submit a PR when I get a chance.

**Comment by brndnmtthws** [comment]
#265 should address this. Feel free to test the `mesosphere/marathon-lb:fix-proxypass-revproxy` Docker image.
