### ISSUE TITLE
upgrading v1.2.2 to v.1.3.1

### ISSUE THREAD

**Issue by pgraemer** [mesosphere/marathon-lb#266]
when i  upgraded my image from 1.2.2 to 1.3.1  no ACLs where created

i've debugged pretty long now and it seems that no MarathonService is appended to MarathonApp.

it looks like SERVICE_PORT_ASSIGNER.get_service_ports(app) returns nothing, therefore no MarathonService is created, further get_apps returns an empty list.

by changing the following lines in utils.py of **ServicePortAssigner.get_service_ports** i could make everything work again:

```python
        ports = filter(lambda p: p is not None,
                       map(lambda p: p.get('port', None),
                           app.get('portDefinitions', []))
                       )
        ports = app.get('ports', [])
        ports = list(ports) # wtf python?
```
the useful line is `app.get('ports', [])`

any ideas or am i missing something?

**update:**
i found #231  does this mean i need to update my marathon? We are running 0.15.5 currently

**Comment by brndnmtthws** [comment]
Yes, you'll need to update Marathon in this case.

I can introduce a PR to make it backward compatible, but you won't get it until the next release.

**Comment by pgraemer** [comment]
i guess its not just me that would love to see this change. :+1:

**Comment by MikeMichel** [comment]
just ran into this too. a marathon version requirement info would be nice.
