### ISSUE TITLE
Support for FRONTEND_TCP and BACKEND_TCP templates

### ISSUE THREAD

**Issue by jodem** [mesosphere/marathon-lb#275]
Hi,

Is it possible to support VHOST feature in TCP mode using sni feature ?

Allows us to have Machine to machine (X509) authentication : ha-proxy do not offload https but is able to route the traffic to the correct back-end.

**Comment by jodem** [comment]
OK so I managed to have it work.

To do so you must use the marathon-lb for this specific M2M purpose since it removes many other feature. I tweaked templates (and config.py) to remove front-end binding. 

Here is the result in ha_proxy.conf :

```
frontend marathon_http_in
  bind *:80
  mode http

frontend marathon_http_appid_in
  bind *:9091
  mode http

# I forced this one in changeing config.py to change default template for https_in !
frontend marathon_https_in
  bind *:443
  mode tcp
  tcp-request inspect-delay 5s
  tcp-request content accept if { req.ssl_hello_type 1 }

# This part is added with vhost feature automatically
  acl application_test-nginx-ssl_cloudv2_sagex3_com_nginx-ssl2_core req.ssl_sni -i test-nginx.cloudv2.sagex3.com 
  use_backend nginx-ssl2_core_10101 if application_test-nginx-ssl_cloudv2_sagex3_com_nginx-ssl2_core 
  acl application_ssl_cloudv2_sagex3_com_nginx-ssl3_core req.ssl_sni -i ssl.cloudv2.sagex3.com 
  use_backend nginx-ssl3_core_10102 if application_ssl_cloudv2_sagex3_com_nginx-ssl3_core 


#No frontend as you can see
 
# Backend generated by simple template 
 backend nginx-ssl2_core_10101  
  balance roundrobin  
  mode tcp 
  server 10_100_13_229_31697 10.100.13.229:31697
  server 10_100_14_205_31560 10.100.14.205:31560
 
 backend nginx-ssl3_core_10102  
  balance roundrobin  
  mode tcp 
  server 10_100_14_117_31515 10.100.14.117:31515
```

and the template updates I did : (for port 0)

"labels": {          
        "HAPROXY_GROUP": "external",
        "HAPROXY_0_VHOST" : "ssl.cloudv2.xxxxxxx.com", 
        "HAPROXY_0_HTTP_FRONTEND_ACL" : "",
        "HAPROXY_0_HTTP_FRONTEND_APPID_ACL" : "",
        "HAPROXY_0_BACKEND_HTTP_OPTIONS" : "",
        "HAPROXY_0_HTTP_FRONTEND_ROUTING_ONLY": "",
        "HAPROXY_0_FRONTEND_BACKEND_GLUE" : "",
        "HAPROXY_0_HTTPS_FRONTEND_ACL" : "  acl application_{cleanedUpHostname} req.ssl_sni -i {hostname} \n  use_backend {backend} if application_{cleanedUpHostname} \n",
        "HAPROXY_0_BACKEND_HEAD" : " \n backend {backend}  \n  balance {balance}  \n  mode tcp \n"
}


So to make it work without changing the config.py I would have need :
- The capacity to set template for **frontend marathon_https_in**
- The capacity to disable frontend mapping for a given port (if you keep frontend they are http because of the vhost and haproxy don't like http frontend bound to tcp backend)

**Comment by brndnmtthws** [comment]
Have you seen this?: https://github.com/brndnmtthws/mlb-nginx-http2

**Comment by brndnmtthws** [comment]
Please reopen the issue if that doesn't solve it for you.

**Comment by jodem** [comment]
It does solve the issue, thanks ! It's better for us not to change the python file 👍 

Could you add a link from the documentation ? It's quite common to need X509 calls for M2M connections, it's an asset for marathon-lb to be able to respond to this need.
