### ISSUE TITLE
marathon-lb scalability

### ISSUE THREAD

**Issue by liorze** [mesosphere/marathon-lb#277]
The documentation suggests running only a few instances of marathon-lb in a cluster. More specifically, not on every node in the cluster. 
Isn't that a major limitation for a load balancer? It restricts the throughput of communication in the cluster, since all data pass through the load balancers.

In addition, dcos uses Minuteman. How does marathon-lb compare to Minuteman?

Thanks

**Comment by brndnmtthws** [comment]
> Isn't that a major limitation for a load balancer?

In practice, not really. HAProxy can handle line-rate provided you aren't using very small payloads or short lived TCP connections. On modern machines that's 10Gbit full-duplex, which you'll have a hard time saturating unless you're actually moving 10Gbit of data around all the time. If so, add N instances where `amount of traffic = N * 10Gbit`. Modern networking gear is quite good, and sometimes the network is actually faster than local disks.

To answer your second question, we have a comparison of the different LBs here in a documentation PR:

https://github.com/dcos/dcos-docs/pull/437

More specifically:

https://github.com/dcos/dcos-docs/blob/759ff4abe25af3afb84a0009abb68bb46a4322d1/1.7/usage/service-discovery/index.md
