### ISSUE TITLE
HA questions

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon-lb#282]
The current recommandation is running only 2 instances of marathon-lb, more will add too much pressure on marathon.
This does not fit with a large cluster, marathon-lb become a bottleneck, as all the traffic need to pass thru only one or two haproxy instances.
We should separate the config generator and haproxy instances, to be able to launch one haproxy per mesos slave.

Even if marathon / marathon-lb are not available ( overload, maintenance ... ) haproxy instances must keep running with a valid configuration.

I guess the best way to achieve this is to evolve marathon-lb to a mesos framework. The scheduler will be responsible to launch haproxy on each slave ( executor ), and dispatch versioned and validated configuration to all executors. 

The scheduler will be the only one to listen to marathon, executors will keep running even if the scheduler died.

What do you think about this ?

**Comment by heww** [comment]
awesome

**Comment by brndnmtthws** [comment]
Can you point to me where there exists a recommendation to run "only 2 instances"? I would change that to say you should run _at least 2 instances_.

You'd also have to have an awful lot of traffic (or a lot of new TLS sessions being created) for MLB to become a bottleneck. 2 or 3 HAProxy instances should have no trouble with several Gbps of traffic, provided the networking infrastructure supports it.

**Comment by vixns** [comment]
You're right, I misread the "at least", maybe because of 

"_Note: do not run marathon-lb on every node in your cluster. This is considered an anti-pattern due to the implications of hammering the Marathon API and excess health checking._"

_every node_ are 3 on a minimal cluster.

You may change this to a more explicit advice, like _Note: do not run more than N marathon-lb instances..._ 

What is the maximum recommended instances count ?

The proposal of splitting the config generator and HAProxy as a framework is more about optimal mesos/marathon integration, resilience and separation of concerns than handling a lot of traffic.

**Comment by brndnmtthws** [comment]
There isn't a strict recommendation for a maximum, but I'd guess that returns would begin to diminish beyond 5 instances (except in special circumstances).

**Comment by brndnmtthws** [comment]
I'm going to close this out, unless you have further questions. I've clarified some of the notes in the README on this topic.

**Comment by mihasya** [comment]
Can you explain "results would begin to diminish"? Is it the "hammering of the Marathon API and excess health checking"? 5 instances of `marathon-lb` is enough to "hammer" the API?

**Comment by brndnmtthws** [comment]
Every running instance of MLB will query the Marathon API (`/v2/apps`, specifically) any time there is a relevant Marathon event (task state change, deployment, etc). If you had, say, 100 instances of MLB and 1000 different apps, Marathon would have to serve up all that task state for every task state change, app definition change, and health check status change. That might, depending on the conditions, result in a DDoS against the Marathon API.
