### ISSUE TITLE
depends on dcos or just straight os mesos & os marathon?

### ISSUE THREAD

**Issue by Ir1sh** [mesosphere/marathon-lb#289]
question is in the title but is this project compatible with the open source builds of mesos and marathon or do you have to be paying for dcos to use this?

thanks

**Comment by h0tbird** [comment]
@Ir1sh I am using it without DC/OS.

**Comment by catherinetcai** [comment]
@h0tbird - Just wondering... how did you set up marathon-lb without DCOS? There's not much documentation out there on how to do it.

**Comment by h0tbird** [comment]
@catherinetcai  I am running one instance of `marathon-lb` for each `worker` node (the ones running the mesos agent). I know this is considered to be an anti-pattern so I might change that in the future. I use a `systemd` unit to start the official `marathon-lb` docker image. Find the code [here](https://github.com/katosys/kato/blob/4038649d25531209afdf74bad25a266bcbcbb5a5/udata/fragments.go#L1297-L1325). Every docker container I run in `mesos` can reach the `marathon-lb` running on the local `worker` by simply connecting to the _'marathon-lb'_ host alias defined [here](https://github.com/katosys/kato/blob/4038649d25531209afdf74bad25a266bcbcbb5a5/udata/fragments.go#L28).
