### ISSUE TITLE
How to eliminate Haproxy ALERT error "sendmsg logger"

### ISSUE THREAD

**Issue by maauso** [mesosphere/marathon-lb#297]
This error appear in https://github.com/mesosphere/marathon-lb/issues/214 and at a glance in https://github.com/mesosphere/marathon-lb/issues/104, we aren't sure if install rsyslog is  "best" solution (and it isn't working for us), then we think that we should  solved this problem.

Everytime that marathon-lb reload HaProxy configuration we can see the same messange error. 

```[ALERT] 231/102635 (263) : sendmsg logger #1 failed: Connection refused (errno=111)
[ALERT] 231/102635 (263) : sendmsg logger #2 failed: Connection refused (errno=111)
[ALERT] 231/102635 (263) : sendmsg logger #1 failed: Connection refused (errno=111)
[ALERT] 231/102635 (263) : sendmsg logger #2 failed: Connection refused (errno=111)
[ALERT] 231/102635 (263) : sendmsg logger #1 failed: Connection refused (errno=111)```

Then this a problem for different reasons, one of these is depends that the number of reloads that you have, your will have a big log useless file.

**Comment by brndnmtthws** [comment]
You can try enabling `/dev/log` this way: https://github.com/mesosphere/marathon-lb/wiki#enabling-haproxy-logging

I believe that will make the warnings go away.

**Comment by brndnmtthws** [comment]
We default the syslog endpoint to `/dev/null` now, so you shouldn't see these anymore.
