### ISSUE TITLE
Marathon-lb with VIPs

### ISSUE THREAD

**Issue by viveksatasiya** [mesosphere/marathon-lb#305]
hello,

I am using custom haproxy as a frontend loadbalancer and my all the backend tasks are running with vips. Everything working fine. now if I want to load balance based on url path in the haproxy configuration, I can not do it because haproxy with VIP works on tcp mode(Layer 4). so how can I achive different vips based load balancing on url path???

Can I run marathon-lb as a frontend loadbalancer with the VIPS?

Thanks

**Comment by brndnmtthws** [comment]
I don't fully understand your question, but I'd recommend _not_ using VIPs with MLB. Using a VIP with MLB will break a number of HAProxy and MLB features.

**Comment by viveksatasiya** [comment]
Thanks for your reply.

I agree with you then If I want to distribute load based on different VIPs, how can I do it with the custom haproxy configurations??

> defaults
  log global
  mode  tcp
  contimeout 50000000
  clitimeout 50000000
  srvtimeout 50000000

> listen appname 0.0.0.0:80
    mode tcp
    balance roundrobin
    server mybackend 1.2.3.4:5000

Above haproxy configuration will send all the traffic to the 1.2.3.4:5000 VIP but If I want to distribute traffic based on domain name, how can I do?

example: 
test.com:80 -> 1.2.3.4:5000
test1.com:80 -> 1.2.3.4:5001

Thanks.

**Comment by brndnmtthws** [comment]
Frankly, if you want to do this, just run HAProxy on its own and don't use MLB.
