### ISSUE TITLE
httplog option only works for service ports?

### ISSUE THREAD

**Issue by edude03** [mesosphere/marathon-lb#306]
Hello, I'm trying to enable the httplog on marathon-lb 1.2.2 (still running 1.7) but I've noticed some odd behaviour. 

I tried the wiki's suggestion to set the haproxy label for the backend as well as setting the frontend as noted in a different issue, however it seems both solutions only work if access the service port IE

```
curl -v localhost:10102 -H "Host: myapp.com"
```

produces 

```
Sep 02 04:46:44 ip-10-0-7-188.ec2.internal haproxy[14797]: 127.0.0.1:46302 [02/Sep/2016:04:46:44.102] server-api_10102 server-api_10102/10_0_1_14_17515 0/0/0/1/1 301 948 - - ---- 3/1/0/1/0 0/0 "GET / HTTP/1.1"
```

but

```
curl -v localhost:80 -H "Host: myapp.com"
```

produces

```
Sep 02 04:46:39 ip-10-0-7-188.ec2.internal haproxy[14797]: Connect from 127.0.0.1:25870 to 10.0.7.188:80 (marathon_http_in/HTTP)
```

So since I want to see logs from clients that connect to the LB from 80/443, is there a way to enable that per app, or do I have to change the` marathon_http_in` template?

**Comment by brndnmtthws** [comment]
It's not enabled by default for port 80, so you'll have to override the template. You just need to add `option httplog` to `HAPROXY_HTTP_FRONTEND_HEAD`: https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_http_frontend_head

**Comment by dariusjs** [comment]
@brndnmtthws sorry to bother on a closed ticket but do you have a specific example for overriding the port 80 template?

I managed to set httplog on the service port with this on my marathon task from an example in another issue you posted
"HAPROXY_0_FRONTEND_HEAD": "frontend {backend}\n  bind {bindAddr}:{servicePort}{sslCert}{bindOptions}\n  mode {mode}\n  option httplog\n"

But I am struggling to find the correct template to be able to add "option httplog" to frontend marathon_http_in bound on port 80

**Comment by brndnmtthws** [comment]
In that case you'll need to override the global template. There's an example for changing a different global option (the TLS versions, in this case) here: https://github.com/mesosphere/marathon-lb/wiki#enabling-tls-v10

**Comment by dariusjs** [comment]
ok thanks will give that a try

**Comment by dariusjs** [comment]
@brndnmtthws  still no luck. What I want to modify is the HAPROXY_FRONTEND_HEAD. I don't want to modify HAPROXY_HEAD as I also have some TCP only endpoints here. Following the TLS example I added this to my task definition:
`  "uris": [
    "file:///etc/haproxy_frontend_template.tgz"
  ],
`
and the content of this gzip tar is 
`frontend {backend}
  bind {bindAddr}:{servicePort}{sslCert}{bindOptions}
  mode {mode}
  option httplog`

I've also tried a plaintext file but that didn't load either.

**Comment by dariusjs** [comment]
I had some misunderstanding on the templates and read things wrong. I need to modify HAPROXY_HTTP_FRONTEND_HEAD as you've mentioned above. For now I was able to follow your example posted here https://docs.mesosphere.com/1.7/usage/service-discovery/marathon-lb/advanced/ by loading the compressed template from the local file system and defining a global configuration for "option httplog"

I struggled on figuring out how to set HAPROXY_HTTP_FRONTEND_HEAD. I tried it on the task, on the MLB by setting the below as well as by loading from an archive but didn't have much luck.

"HAPROXY_HTTP_FRONTEND_HEAD": "frontend marathon_http_in\n  bind *:80\n mode http\n  option httplog\n",

**Comment by dariusjs** [comment]
I have resolved my issue. I was trying to be a bit fancy :( . The way the archive is created must be exactly as per the instructions.

You need to configure this
#!/bin/bash

mkdir -p templates
cat >templates/HAPROXY_HTTP_FRONTEND_HEAD <<EOL
frontend marathon_http_in
  bind *:80
  mode http
  option httplog
EOL

tar czf templates.tgz templates/


I had this originally
#!/bin/bash

mkdir -p templates_frontend
cat >templates_frontend/HAPROXY_HTTP_FRONTEND_HEAD <<EOL
frontend marathon_http_in
  bind *:80
  mode http
  option httplog
EOL

tar czf templates_frontend.tgz templates_frontend/
