### ISSUE TITLE
Ability to choose between '-sf' and '-st' HAProxy signal flags

### ISSUE THREAD

**Issue by h0tbird** [mesosphere/marathon-lb#318]
`marathon-lb` has the `-sf` flag hard-coded. Would you consider making it configurable?
I think this will be useful to people running long-lived TCP connections.

Ideally I would add a timeout to the `-sf` flag after which it will fail-over to the `-st` behavior. But this is a request for the upstream HAProxy project. What do you think?

**Comment by brndnmtthws** [comment]
I'm not opposed to it, but I think I prefer #321.

**Comment by h0tbird** [comment]
I think it will work for me too.
