### ISSUE TITLE
iptables DROP rules not removed

### ISSUE THREAD

**Issue by alenkacz** [mesosphere/marathon-lb#322]
Sometimes it happens, that iptables DROP rules are not removed, we think that it is caused by marathon-lb

`6156  369K DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:9090 flags:0x17/0x02`

We think that this problem happens during the marathon-lb startup, to be more precise on these lines of code - if there is an error between creating and removing iptables rules, they are left behind...

https://github.com/mesosphere/marathon-lb/blob/master/service/haproxy/run#L32-L36

**Comment by bakstad** [comment]
👍 

We have also seen this. Also happens if there is lots of events from marathon.

**Comment by alenkacz** [comment]
Awesome :) any idea when this is going to be released?
