### ISSUE TITLE
iptables: Bad rule (does a matching rule exist in that chain?).

### ISSUE THREAD

**Issue by khvidberg** [mesosphere/marathon-lb#325]
This happens after marathon-lb has run for a while in our Marathon cluster setup.
Marathon-lb is running inside docker, that is executed as a Marathon task.
After this, it will not recover again.

Looking in the iptables the chain "Docker" contained no entries.

...
[ALERT] 270/140434 (4638) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #2 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #2 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #2 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 270/140434 (4638) : sendmsg logger #2 failed: No such file or directory (errno=2)
Configuration file is valid
ok: run: /marathon-lb/service/haproxy: (pid 4628) 1s
iptables: Bad rule (does a matching rule exist in that chain?).
Reloading haproxy
Configuration file is valid

**Comment by khvidberg** [comment]
Forgot to say this was running marathon-lb v1.3.5

**Comment by bakstad** [comment]
We also have problems with something like this.

When you say "will not recover" what do you mean?

Our problem is that marathon-lb seem to stop processing events from marathon. This causes any new instances / changes done  by marathon to not be reflected in haproxy.
