### ISSUE TITLE
1.4.0/1 does not start in poll mode

### ISSUE THREAD

**Issue by sauliusvl** [mesosphere/marathon-lb#334]
It errors out with `/marathon-lb/run: line 104: ARGS: unbound variable`, which indeed seems to be the case: https://github.com/mesosphere/marathon-lb/blob/v1.4.1/run#L83 and thus due to the `set -euo pipefail` the script terminates.

**Comment by brndnmtthws** [comment]
I'm probably just going to remove the poll and event modes, to be honest. It's too difficult to maintain so many different pathways. In the future I'm only going to support SSE.

Regardless, 09d228cbbb435caf95743a07de2eb667b5f7e5c8 should resolve this.
