### ISSUE TITLE
Using zdd.py with host networking

### ISSUE THREAD

**Issue by JamieCressey** [mesosphere/marathon-lb#335]
Hey guys, great app you have here, I'm really enjoying getting up to speed with it.

I have a service config which looks something like;

```
{
  "id": "/app.foo.net/492dd49a1aa2",
  "cmd": null,
  "cpus": 0.5,
  "mem": 1024,
  "disk": 0,
  "instances": 1,
  "container": {
    "docker": {
      "image": "app.foo.net:492dd49a1aa2-10",
      "network": "HOST",
      "forcePullImage": false
    },
    "type": "DOCKER"
  },
  "uris": [
    "file:///etc/docker.tar.gz"
  ],
  "env": {
  },
  "labels": {
    "HAPROXY_DEPLOYMENT_GROUP": "app.foo.net",
    "HAPROXY_GROUP": "external",
    "HAPROXY_0_SSL_CERT": "/etc/ssl/certs/star.foo.net.crt",
    "HAPROXY_DEPLOYMENT_ALT_PORT": "11000",
    "HAPROXY_0_VHOST": "app.foo.net"
  },
  "portDefinitions": [
    {
      "port": 0,
      "protocol": "tcp",
      "name": "HTTP",
      "labels": null
    },
    {
      "port": 0,
      "protocol": "tcp",
      "name": "JMX",
      "labels": null
    }
  ],
  "healthChecks": [
    {
      "protocol": "TCP",
      "portIndex": 0,
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3
    }
  ]
}
```

When I run the `zdd.py` script I get the following error;

```
Traceback (most recent call last):
  File "./zdd.py", line 807, in <module>
    if do_zdd(args):
  File "./zdd.py", line 678, in do_zdd
    new_app = prepare_deploy(args, previous_deploys, app)
  File "./zdd.py", line 615, in prepare_deploy
    next_port = get_service_port(app)
  File "./zdd.py", line 500, in get_service_port
    return int(app['ports'][0])
KeyError: 'ports'
```

I assume this is because I don't specify a `servicePort`, rather let Marathon chose a random one for me. However, to set a servicePort when using host networking mode, my understanding is a just need to create an array called `servicePort` and set one there. Even doing this does not work as the zdd.py script is looking in either the `ports` array or `portMappings` hash, neither are really applicable for a service running in host network mode.

Is there something I'm missing?

Thank you in advanced!

**Comment by brndnmtthws** [comment]
You should probably specify a service port. The implications of not doing so are that it may occasionally fail.

That said, this should work and it might have to do with recent changes to the Marathon API. What version of Marathon are you running?

**Comment by JamieCressey** [comment]
I probably should have included that in my original post :) 

This was failing on 1.3.1. I since upgraded to 1.3.2 but also modified my service config to use Docker bridged mode instead (as to not hold up my deployment) so I don't know if it's still an issue in 1.3.2. I'll test and confirm.

**Comment by JamieCressey** [comment]
Still the same problem. I think this may be caused by https://github.com/mesosphere/marathon-lb/blob/master/zdd.py#L495 and https://github.com/mesosphere/marathon-lb/blob/master/zdd.py#L503 not getting/setting from `app['portDefinitions'][0]['servicePort']` which should be used in HOST network mode, correct?

I've made the changes locally to my copy of `zdd.py` and it seems to have done the trick, if you're happy this is the correct fix I'm happy to put a PR in.

**Comment by brndnmtthws** [comment]
@JamieCressey yeah, if you could open a PR that would be wonderful. If you could also capture the regression in a unit test, that'd be 💯
