### ISSUE TITLE
version:1.4.1 has errors : ./run: 4: ./run: Syntax error: "(" unexpected and so on

### ISSUE THREAD

**Issue by tanglianggithub** [mesosphere/marathon-lb#337]
errors:
```
Starting task haproxy_-test.5843aef1-8f5d-11e6-87c9-024265313836
./run: 4: ./run: Syntax error: "(" unexpected
Reloading haproxy
cat: /tmp/haproxy.pid: No such file or directory
[ALERT] 284/024941 (29) : Could not open configuration file /marathon-lb/haproxy.cfg : No such file or directory
./run: 4: ./run: Syntax error: "(" unexpected
```

**Comment by deric** [comment]
Having the same issue, problem seems to be with CLI arguments parsing, `bash -x`:
```
+ '[' -n 9090,9091,4080,4443 ']'
+ echo 9090,9091,4080,4443
+ '[' -n 2m ']'
+ echo 2m
+ declare -i ssl_certs_pos=0
+ (( i=1 ))
+ (( i<=6 ))
+ '[' sse = --ssl-certs ']'
+ (( i++ ))
+ (( i<=6 ))
+ '[' --marathon = --ssl-certs ']'
+ (( i++ ))
+ (( i<=6 ))
+ '[' http://localhost:8080 = --ssl-certs ']'
+ (( i++ ))
+ (( i<=6 ))
+ '[' --group = --ssl-certs ']'
+ (( i++ ))
+ (( i<=6 ))
+ '[' LICENSE Longhelp.md Makefile README.md __pycache__ bluegreen_deploy.py bluegreen_deploy.pyc build-haproxy.sh common.py common.pyc config.py getconfig.lua getmaps.lua getpids.lua lrucache.py marathon_lb.py marathon_lb.pyc requirements.txt run service signalmlb.lua templates utils.py zdd.py zdd_exceptions.py = --ssl-certs ']'
/marathon-lb/run: line 30: [: too many arguments
+ (( i++ ))
+ (( i<=6 ))
+ '[' --dry = --ssl-certs ']'
+ (( i++ ))
+ (( i<=6 ))
+ '[' 0 -gt 0 ']'
+ SSL_CERTS=/etc/ssl/cert.pem
+ '[' -n '' ']'
+ '[' 0 -eq 0 ']'
```
the original command was:
```
docker run --privileged -e PORTS="9090,9091,4080,4443" --net=host \
        -e HAPROXY_RELOAD_SIGTERM_DELAY="2m" \
        -v /etc/sv/marathon-lb/templates:/marathon-lb/templates\
        -v /etc/nginx/ssl:/certs\
        marathon-lb:1.4.1 sse --marathon http://localhost:8080 --group "*"
```

**Comment by brndnmtthws** [comment]
@tanglianggithub what arguments are you passing?

**Comment by brndnmtthws** [comment]
Please test with the `disable-globbing-in-run` image tag to see if that resolves this for you.

**Comment by tanglianggithub** [comment]
@brndnmtthws arguments are /marathon-lb/marathon_lb.py     --syslog-socket /dev/null     --haproxy-config /marathon-lb/haproxy.cfg     --ssl-certs "/etc/ssl/cert.pem"     --command "sv reload /marathon-lb/service/haproxy"     --sse   --marathon http://*.*.*.*:10001 --group zzzc --skip-validation --auth-credentials * --dont-bind-http-https --log-format %(asctime)s- %(levelname)s - %(message)s

**Comment by tanglianggithub** [comment]
python3.5.2+ has error when requesting  "http://hostname:10001/v2/events"
should set python version in dockerfile   @brndnmtthws 
error is as follows:
`resp = requests.get(url,stream=True,headers=headers,timeout=(3.05, 46))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x7f3823a48358>, 'Connection to . . ..  timed out. (connect timeout=3.05)')`

**Comment by deric** [comment]
@brndnmtthws `disable-globbing-in-run` branch looks good. I haven't test it on real traffic yet, but arguments parsing seems to be working. Thanks Brenden!

Any chance to draft a new release soon?
