### ISSUE TITLE
Marathon Authentication

### ISSUE THREAD

**Issue by WalterDalton** [mesosphere/marathon-lb#34]
Can we add a principal and secret_file_location flag so if our marathon is asking for authentication, we can provide it?

**Comment by brndnmtthws** [comment]
Did you try passing the values as part of the Marathon URL? Something like this: `http://user:pass@marathon/`

**Comment by WalterDalton** [comment]
I considered that, but then my username/password would be on the commandline (and thus readable by all users using the ps command).  The ideal situation would be be consistent with Mesos, Marathon, and Chronos with the ability to provide a location to the file that contains the secret.   This would allow users to provide only the location, and leave it up to them on file system permissions etc to ensure security.   Only having an option that displays the password on the command line, that displays in the ps command, doesn't provide the security that authentication in marathon is supposed to provide.

**Comment by lloesche** [comment]
Seems like this issue is resolved by PR #52
