### ISSUE TITLE
Examples on path based routing

### ISSUE THREAD

**Issue by girishbhat77hub** [mesosphere/marathon-lb#340]
Can someone please include samples on performing path based routing such that applications are accessible via paths like http://mydomain.com/application1 and http://mydomain.com/application2. Have tried setting "HAPROXY_0_VHOST": "mydomain.com" and "HAPROXY_0_PATH": "application1", but doesn't work.

**Comment by brndnmtthws** [comment]
There are a couple examples conveniently located in the documentation: https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_n_path
