### ISSUE TITLE
Error in v1.4.1 docker container during config reload

### ISSUE THREAD

**Issue by toofishes** [mesosphere/marathon-lb#341]
It looks like there was a change from `getvhostmap` to `getmaps` in commit 75d9b08ea7, but there is still some reference to the old thing hanging around. I see `getvhostmap` still present in config.py, so that might be it.

```
marathon_lb: running config is different from generated config - reloading
marathon_lb: writing temp file /tmp/tmptv0gefgv that will replace /marathon-lb/haproxy.cfg
marathon_lb: checking config with command: ['haproxy', '-f', '/tmp/tmptv0gefgv', '-c']
[ALERT] 286/213206 (594) : parsing [/tmp/tmptv0gefgv:18] : error in lua file '/marathon-lb/getvhostmap.lua': cannot open /marathon-lb/getvhostmap.lua: No such file or directory
[ALERT] 286/213206 (594) : parsing [/tmp/tmptv0gefgv:45] : error detected in proxy 'stats' while parsing 'http-request use-service' rule : 'lua.getvhostmap' unknown service name..
[ALERT] 286/213206 (594) : Error(s) found in configuration file : /tmp/tmptv0gefgv
marathon_lb: haproxy returned non-zero when checking config
marathon_lb: skipping reload: config not valid
marathon_lb: updating tasks finished, took 0.03157377243041992 seconds
```

We're running with a command string like the following, in the docker container, with some custom templates:

    /marathon-lb/run sse --health-check --ssl-certs $SSL_CERTS --marathon $MARATHON_URL --group $GROUP

**Comment by toofishes** [comment]
Just to add more details: Downgrading to v1.3.5 of the container "fixes" this- no error there.

**Comment by brndnmtthws** [comment]
Are you using any custom templates? I'm not seeing any references to the old file in the code.

**Comment by toofishes** [comment]
Ugh, totally missed this the first time, sorry. Found this in our custom `HAPROXY_HEAD` template:

    lua-load /marathon-lb/getvhostmap.lua

I'll clean that up by making any necessary updates to the current defaults, and try again.
