### ISSUE TITLE
More than one basic auth configured leads to unreachable service

### ISSUE THREAD

**Issue by PascalPflaum** [mesosphere/marathon-lb#342]
Using mesosphere/marathon-lb:v1.4.1 via DCOS 1.8

We tried to secure more than one service with basic authentication.
It works fine with one service protected by basic auth.

If we add the HAPROXY_0_AUTH label to the second service, this service is unreachable.
We traced down the issue to a wrongly written HAProxy frontend.

```
frontend marathon_https_in
  bind *:443 ssl crt /mnt/mesos/sandbox/AAAAAA-crt-with-key.pem crt /mnt/mesos/sandbox/BBBBBBB-crt-with-key.pem
  mode http
  acl auth_development-alertmanager_AAAAAA_de_infra_alertmanager http_auth(user_infra_alertmanager_10106)
  http-request auth realm "realm" if { ssl_fc_sni development-alertmanager.AAAAAA.de } !auth_development-alertmanager_AAAAAA_de_infra_alertmanager
  use_backend infra_alertmanager_10106 if { ssl_fc_sni development-alertmanager.AAAAAA.de }
  use_backend %[ssl_fc_sni,lower,map(/marathon-lb/domain2backend.map)]
  acl auth_development-prometheus_AAAAAA_de_infra_prometheus http_auth(user_infra_prometheus_10105)
  http-request auth realm "realm" if { ssl_fc_sni development-prometheus.AAAAAA.de } !auth_development-prometheus_AAAAAA_de_infra_prometheus
  use_backend infra_prometheus_10105 if { ssl_fc_sni development-prometheus.AAAAAA.de }
```

IMO the line use_backend %[ssl_fc_sni,lower,map(/marathon-lb/domain2backend.map)] has to be at the end of the block and is the reason that the second service is unreachable.

**Comment by SlevinBE** [comment]
Experiencing the same issue, but in a different scenario.
We have multiple services with basic authentication, but wanted to add one without authentication.
This resulted in the same issue where the following use_backend for the domain2backend.map got added in between the other records (similar to what @PascalPflaum posted).
```
use_backend %[req.hdr(host),lower,regsub(:.*$,,),map(/marathon-lb/domain2backend.map)]
```
Adding this to the end of the section fixed it (until another marathon-lb reload happened)

**Comment by SlevinBE** [comment]
I opened a PR (#342) for this one. Let me know if something can be improved in it.
