### ISSUE TITLE
configuration of SSL Ports

### ISSUE THREAD

**Issue by sdechi** [mesosphere/marathon-lb#345]
Hi, 

I installed GitLab as explained in https://mesosphere.com/blog/2016/09/16/gitlab-dcos/
Then secured my server with a letsencrypt cert. (https://github.com/mesosphere/letsencrypt-dcos)
The main feature of gitlab that I want to use is the registry. This is on port 50000 as it is in the standard installation. 

When I try to access the registry from Jenkins, tls: oversized record received with length 20527 
Is there a  way to change the behavior of the marathon-lb so that the right cert is provided? 

Thanks,
Sascha

**Comment by brndnmtthws** [comment]
You just need to set the cert on your backend:

`HAPROXY_0_SSL_CERT=/etc/ssl/cert.pem`
