### ISSUE TITLE
Label HAPROXY_0_HTTP_BACKEND_NETWORK_ALLOWED_ACL is not working

### ISSUE THREAD

**Issue by mvanholsteijn** [mesosphere/marathon-lb#346]
Hi I am using the marathon-lb (1.4.1) and it does not pick up the label HAPROXY_0_HTTP_BACKEND_NETWORK_ALLOWED_ACL as documented. 

I expected:
```
acl restricted_network hdr_ip(X-Forwarded-For) {network_allowed}
```
but got the default:
```
http-request allow if network_allowed
```

 If I specify HAPROXY_0_HTTP_BACKEND_OPTIONS they are processed.

What am I doing wrong?

[marathon.json](https://github.com/mesosphere/marathon-lb/files/541520/marathon.txt)

**Comment by brndnmtthws** [comment]
I tested your app config, verbatim. It seems to work fine for me. Here's the backend definition:

```
core@ip-10-0-7-122 ~ $ curl marathon-lb.marathon.mesos:9090/_haproxy_getconfig

...

frontend paas-monitor_10104
  bind *:10104
  mode http
  use_backend paas-monitor_10104

backend paas-monitor_10104
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  acl network_allowed src 192.168.1.11/32
  http-request allow if network_allowed
  http-request deny
  option  httpchk GET /health
  timeout check 2s
  server 10_0_0_249_9029 10.0.0.249:9029 check inter 10s fall 4
```

So yeah, IDK what you're doing wrong.

**Comment by brndnmtthws** [comment]
Woops, I take that back. I have a problem with reading comprehension.

Yeah, it's busted. Let me follow-up with a PR.

**Comment by mvanholsteijn** [comment]
The responsibility always lies with the writer :-) So, I have updated the wording. Hopefully for the better.

**Comment by brndnmtthws** [comment]
Go ahead and test out the `fix-acl-labels` image tag with these labels:

```json
{
  "labels": {
    "HAPROXY_GROUP": "external",
    "HAPROXY_0_VHOST": "paas-monitor.127.0.0.1.xip.io",
    "HAPROXY_0_HTTP_BACKEND_NETWORK_ALLOWED_ACL": "  acl network_allowed hdr_ip(X-Forwarded-For) {network_allowed}\n",
    "HAPROXY_0_BACKEND_NETWORK_ALLOWED_ACL": "192.168.1.11/32"
  }
}
```

**Comment by mvanholsteijn** [comment]
working nicely with v1.4.2!
