### ISSUE TITLE
Marathon-lb deployed: "Unexpected error"

### ISSUE THREAD

**Issue by trav-pf** [mesosphere/marathon-lb#355]
Deployed mesosphere/marathon-lb:v1.4.1 via DCOS 1.8.4 after setting up a calico network according to
https://www.projectcalico.org/calico-dcos-demo-security-speed-and-no-more-port-forwarding/

Marathon-lb keeps being deployed forever and being "unhealthy".

Content of the log from "Services":

`--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S0.53e7c6fc-7328-46a6-bc76-f0e92ddcaf56" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S0/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.7223808d-9791-11e6-b566-70b3d5800007/runs/53e7c6fc-7328-46a6-bc76-f0e92ddcaf56" --stop_timeout="20secs"
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S0.53e7c6fc-7328-46a6-bc76-f0e92ddcaf56" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S0/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.7223808d-9791-11e6-b566-70b3d5800007/runs/53e7c6fc-7328-46a6-bc76-f0e92ddcaf56" --stop_timeout="20secs"
Registered docker executor on 10.64.56.8
Starting task marathon-lb.7223808d-9791-11e6-b566-70b3d5800007
setting sysctl params to: net.ipv4.tcp_tw_reuse=1 net.ipv4.tcp_fin_timeout=30 net.ipv4.tcp_max_syn_backlog=10240 net.ipv4.tcp_max_tw_buckets=400000 net.ipv4.tcp_max_orphans=60000 net.core.somaxconn=10000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_syn_backlog = 10240
net.ipv4.tcp_max_tw_buckets = 400000
net.ipv4.tcp_max_orphans = 60000
net.core.somaxconn = 10000
Reloading haproxy
cat: /tmp/haproxy.pid: No such file or directory
[ALERT] 294/132245 (185) : Could not open configuration file /marathon-lb/haproxy.cfg : No such file or directory
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS_WITH_PATH
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_REQUEST_ONLY
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_OPTIONS
marathon_lb: setting default value for HAPROXY_MAP_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REVPROXY_GLUE
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_PROXYPASS_GLUE
marathon_lb: setting default value for HAPROXY_BACKEND_HSTS_OPTIONS
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_BACKEND_STICKY_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_FRONTEND_BACKEND_GLUE
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_AUTH
marathon_lb: setting default value for HAPROXY_BACKEND_HEAD
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_USERLIST_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REDIR
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY
marathon_lb: starting event processor thread
marathon_lb: SSE Active, trying fetch events from http://master.mesos:8080/v2/events
marathon_lb: fetching apps
marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1520, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1349, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 121, in get_service_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
marathon_lb: received event of type event_stream_attached
marathon_lb: received event of type event_stream_detached
`

**Comment by brndnmtthws** [comment]
This should be addressed by #352. Give that a shot.

**Comment by trav-pf** [comment]
I tried again today with available version 1.4.1 from Universe, same error as last time:

`--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S6.bba7b383-b7d4-4686-ac49-f885810c5ba4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S6/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007/runs/bba7b383-b7d4-4686-ac49-f885810c5ba4" --stop_timeout="20secs"
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S6.bba7b383-b7d4-4686-ac49-f885810c5ba4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S6/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007/runs/bba7b383-b7d4-4686-ac49-f885810c5ba4" --stop_timeout="20secs"
Registered docker executor on 10.64.56.3
Starting task marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007
setting sysctl params to: net.ipv4.tcp_tw_reuse=1 net.ipv4.tcp_fin_timeout=30 net.ipv4.tcp_max_syn_backlog=10240 net.ipv4.tcp_max_tw_buckets=400000 net.ipv4.tcp_max_orphans=60000 net.core.somaxconn=10000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_syn_backlog = 10240
net.ipv4.tcp_max_tw_buckets = 400000
net.ipv4.tcp_max_orphans = 60000
net.core.somaxconn = 10000
Reloading haproxy
cat: /tmp/haproxy.pid: No such file or directory
[ALERT] 297/054245 (184) : Could not open configuration file /marathon-lb/haproxy.cfg : No such file or directory
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY
marathon_lb: setting default value for HAPROXY_FRONTEND_BACKEND_GLUE
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REDIR
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_REQUEST_ONLY
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_MAP_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_HEAD
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_PROXYPASS_GLUE
marathon_lb: setting default value for HAPROXY_BACKEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REVPROXY_GLUE
marathon_lb: setting default value for HAPROXY_USERLIST_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_STICKY_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS_WITH_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_HSTS_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_HEAD
marathon_lb: starting event processor thread
marathon_lb: fetching apps
marathon_lb: SSE Active, trying fetch events from http://master.mesos:8080/v2/events
marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1520, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1349, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 121, in get_service_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
marathon_lb: received event of type event_stream_attached
marathon_lb: received event of type failed_health_check_event
marathon_lb: received event of type failed_health_check_event
marathon_lb: received event of type failed_health_check_event
Received killTask for task marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007
marathon_lb: received event of type unhealthy_task_kill_event
`
