### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by robsonpeixoto** [mesosphere/marathon-lb#359]
The haproxy are stressing the CPU

![image](https://cloud.githubusercontent.com/assets/124390/19685200/af9afc04-9a91-11e6-8095-f90a7b6d4b5d.png)

Do you have any idea how to solve it?

**Comment by robsonpeixoto** [comment]
The `lsof` show a connection between `mesos-lb-3` and `leia-4` with the status `CLOSE_WAIT`.
I made a ssh to `leia-4` and tried to find out the process how are listen the port `31867` but the process do not exists.

```bash
mesos-lb-3:~# lsof -i | grep 73610
haproxy 73610    root  427u  IPv4 211721139      0t0  TCP mesos-lb-3.my-domain:55363->leia-4.my-domain:31867 (CLOSE_WAIT)
haproxy 73610    root  450u  IPv4 211724964      0t0  TCP mesos-lb-3.my-domain:55401->leia-4.my-domain:31867 (CLOSE_WAIT)


leia-4:~# lsof -i | grep 31867
```

**Comment by brndnmtthws** [comment]
Interesting. You may want to try sending a SIGTERM to haproxy by setting HAPROXY_RELOAD_SIGTERM_DELAY as noted in the readme.

**Comment by robsonpeixoto** [comment]
@brndnmtthws  But what's will happen with my persistent connections ?
The 100% of CPU usage only happens when the haproxy process has only `CLOSE_WAIT` connections. There are a lot of old process with open connections.

**Comment by brndnmtthws** [comment]
That will indeed cause persistent connections to be dropped. I'm not sure what's causing the high CPU use, but it sounds like an haproxy bug.
