### ISSUE TITLE
poll mode removed ?

### ISSUE THREAD

**Issue by scalp42** [mesosphere/marathon-lb#36]
I believe `POLL_INTERVAL` is not read anywhere with current master.

Due to https://github.com/mesosphere/marathon-lb/issues/35 I'm trying to switch to polling every sec or so, but I don't see any flag.

**Comment by pgraemer** [comment]
POLL_INTERVAL can be found here; https://github.com/mesosphere/marathon-lb/blob/master/run#L78

**Comment by lloesche** [comment]
@scalp42 the env var is only being used as part of the Docker container run script. If you invoke the Python script directly it's up to you to poll yourself using e.g. cron, systemd timer or a custom script.
