### ISSUE TITLE
Only get "503 Service Unavailable  No server is available to handle this request." when  browse http://<my_marathon-lb_ip>:9090/_haproxy_getappmap

### ISSUE THREAD

**Issue by xwtqin** [mesosphere/marathon-lb#361]
Only get "503 Service Unavailable  No server is available to handle this request." when i browse http://<my_marathon-lb_ip>:9090/_haproxy_getappmap. I have launched marathon-lb with args set "sse -m http://<my_marathon_ip>:8080 --group external --haproxy-map" on marathon UI. And there are also a nginx app with  ID "/nginx-external" and labels "HAPROXY_GROUP=external, HAPROXY_0_VHOST=test-app.nginx.com" on marathon UI, running healthily.However, I can get the value of _haproxy_getvhostmap  except _haproxy_getappmap.

**Comment by brndnmtthws** [comment]
Is MLB running with `--haproxy-map`?

**Comment by xwtqin** [comment]
Yes, I also set MLB with --haproxy-map.

发自我的 iPhone

**Comment by brndnmtthws** [comment]
Seems to work fine for me. Which version of MLB?

**Comment by xwtqin** [comment]
I am using the image mesosphere/marathon-lb, which is pulled 3 months  ago, on July 26th.

**Comment by xwtqin** [comment]
I pull the most recent image today.However, I still cann't get the value of _haproxy_getappmap.

**Comment by xwtqin** [comment]
The problem is solved today, using the new MLB image with --haproxy-map. It is my carelessness that I pulled the most recent image yesterday but forgot setting the argument of  --haproxy-map.
