### ISSUE TITLE
Docs should mention "-v /dev/log:/dev/log" required for haproxy journald logs

### ISSUE THREAD

**Issue by matt-deboer** [mesosphere/marathon-lb#364]
When run as a docker container (a common deployment scenario), logs for the embedded haproxy will not be available unless `/dev/log` is mounted within this container.

This is just a note requesting that it be mentioned somewhere in the docs.

**Comment by brndnmtthws** [comment]
It's on the wiki:

https://github.com/mesosphere/marathon-lb/wiki#enabling-haproxy-logging

It's a little too detailed for the readme, and there's a link to the wiki from the readme.

**Comment by matt-deboer** [comment]
my bad; the github "search" box doesn't index the wiki, so I missed it

**Comment by brndnmtthws** [comment]
No sweat, it's not easy to find.
