### ISSUE TITLE
HowTo SSL-Termination on DC/OS

### ISSUE THREAD

**Issue by dArignac** [mesosphere/marathon-lb#372]
Hi there,

I'm trying to configure the marathon-lb to do SSL termination but did not find any documentation on this. Is this possbile and if, how?

Thanks!

**Comment by robsonpeixoto** [comment]
@dArignac https://github.com/mesosphere/marathon-lb#providing-ssl-certificates

**Comment by dArignac** [comment]
Ah alright, thank you!
How would I define the ```HAPROXY_SSL_CERT ``` within an options file? with ```"env"```?

```
{
  "marathon-lb": {
    "name": "marathon-lb-external",
    "instances": 1,
    "haproxy-group": "external",
    "bind-http-https": true,
    "role": "slave_public",
    "env": {
      "HAPROXY_SSL_CERT": "<MYCERT>"
    }
  }
}
```

**Comment by dArignac** [comment]
Hi there,

I solved it by updating an existing marathon-lb instance via the REST API updating the applications "env" and setting ```HAPROXY_SSL_CERT``` to the certificate content.

Basically this can be done as in this script: https://github.com/mesosphere/letsencrypt-dcos/blob/master/post_cert.py
