### ISSUE TITLE
Front end application using HOST network mode with Marathon-LB Does not Work

### ISSUE THREAD

**Issue by krishnabigdata** [mesosphere/marathon-lb#376]
Hi,

Front end application using HOST network mode with Marathon-LB Does not Work.

Regards,
Krishna.

**Comment by brndnmtthws** [comment]
Could you please elaborate? Maybe provide the app definition?

**Comment by krishnabigdata** [comment]
Hi,

Here is my marathon job json. I used auto-assign service port during marathon-lb deployment.

**Service Discovery doesn't work in HOST network.**
```
{
  "id": "/hello",
  "cmd": "node /src/server.js",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "nodejs-sample",
      "network": "HOST",
      "privileged": true
    }
  },
  "labels":{
    "HAPROXY_GROUP":"external"    ,
    "HAPROXY_0_VHOST":"hello.service.com"
  }
}
```
**Service Discovery Works in BRIDGE Network.**

```
{
  "id": "/hello",
  "cmd": "node /src/server.js",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "nodejs-sample",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 4000,
          "hostPort": 0
        }
      ],
      "privileged": true
    }
  },
  "labels":{
    "HAPROXY_GROUP":"external"    ,
    "HAPROXY_0_VHOST":"hello.service.com"
  }
}
```

Regards,
Krishna.

**Comment by brndnmtthws** [comment]
Does your app bind to `$PORT0`?

**Comment by krishnabigdata** [comment]
Hi,

Yes, here is my updated config.

{
  "id": "/hello",
  "cmd": "node /src/server.js",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "nodejs-sample",
      "network": "HOST",
      "privileged": true
    }
  },
  "labels":{
    "HAPROXY_GROUP":"external"    ,
    "HAPROXY_0_VHOST":"hello.service.com"
  },
  "portDefinitions": [
    {
      "port": 4000
    }
  ]
}

Added to it, the service is not getting recognized/shown in marathon-lb web UI.
 
Regards,
Krishna.

**Comment by brndnmtthws** [comment]
Yes to what? The nodejs app binds to `$PORT0`? Can you paste the snippet of code which proves that? Why is the container running in privileged mode?

**Comment by krishnabigdata** [comment]
Here is the $PORT0 of app.

```
 "portDefinitions": [
    {
      "port": 4000
    }
  ]
```
You are requesting service definition port of APP or PORT of marathon-lb? privileged is not mandate, you can ignore it. Can you please share the a marathon json config for HOST app deployment where the service discovery works using marathon-lb.

Regards,
Krishna.

**Comment by brndnmtthws** [comment]
I think you need to educate yourself on how ports work in Marathon. Your app must bind to `$PORT0` (that's an environment variable). Here's some documentation:

https://mesosphere.github.io/marathon/docs/ports.html

Good luck!

**Comment by krishnabigdata** [comment]
Hi,

First of all, If I know the answer why would I ask you. The reason I requested, because what parameter we need to use to make the marathon-lb to discover the port of the app which is running in HOST network, because I tried different option as per the documentation- "Example Configuration
Host Mode".  

My Question was very clear and shared the config I am using. Its just missing is the environment variable, which you could have mentioned. Anyways thanks for your response.

**Sorry to say this, the way you communicated is not a good way to do it**

As per your documentation, You can also refer here "Example Configuration-Host Mode". 

Regards,
Krishna.
