### ISSUE TITLE
Allow to specify log level via env variables

### ISSUE THREAD

**Issue by marcinjedyk-msm** [mesosphere/marathon-lb#387]
By default log level is set to DEBUG which makes marathon-lb very noisy in environments where deployments are frequent (few per hour). Allow to specify log level via i.e. HAPROXY_LOG_LEVEL environment variable

**Comment by brndnmtthws** [comment]
You can change it on the command line with `--log-level`, as per https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#command-line-usage.
