### ISSUE TITLE
Workaround to export a tcp app

### ISSUE THREAD

**Issue by pdiniz13** [mesosphere/marathon-lb#397]
This is a duplicate of a closed issue https://github.com/mesosphere/marathon-lb/issues/275. I need to export a tcp but the only way to do so is via vhosts which don't currently support vhosts. I tried using some of the templates from https://github.com/brndnmtthws/mlb-nginx-http2 but he has a warning that this will break This configuration breaks TLS termination at MLB for all other apps as well as not being able to use routing by path which we need.

**Comment by sfwn** [comment]
do you have any workaround already?

i occurred the same issue. I want to expose a `mysql` via VHOST.

**Comment by jkoelker** [comment]
Apologies for the delay in getting to you. I'm not sure the status back when the question was originally posed, but currently you can expose a TCP app by setting [`HAPROXY_{n}_MODE`](https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_n_mode) to 'tcp'.
