### ISSUE TITLE
Marathon-lb does not respect Marathon's health checks

### ISSUE THREAD

**Issue by brndnmtthws** [mesosphere/marathon-lb#4]
See title.

**Comment by brndnmtthws** [comment]
Example implementation might be:

```patch
diff --git a/marathon-update-haproxy.py b/marathon-update-haproxy.py
index 1f1657c..e9e18ae 100755
--- a/marathon-update-haproxy.py
+++ b/marathon-update-haproxy.py
@@ -969,6 +969,9 @@ def get_apps(marathon):
                                task['id'])
                 continue

+            if len(task['healthCheckResults']) > 0 && !task['healthCheckResults'][0]['alive']:
+                continue
+
             task_ports = task['ports']

             # if different versions of app have different number of ports,
```

**Comment by brndnmtthws** [comment]
cc @discordianfish

**Comment by felixb** [comment]
this should at least be optional.

we use haproxies health checks. it is more accurate because health checks don't need to trickle down the service discovery to be reflected in backend selection.

**Comment by brndnmtthws** [comment]
I wrote a more complete patch, but I can't currently push my branch. It's here:

https://gist.github.com/brndnmtthws/745af26d579fea82bc18

I did not make it optional to observe the health check.

**Comment by ianpward** [comment]
@brndnmtthws please resolve this issue
