### ISSUE TITLE
Ensure that setting `--group "*"` matches only apps that have an HAPROXY_GROUP label defined and ignore apps that don't have it defined.

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/marathon-lb#403]
Currently,  passing the command line argument `--group "*"` to Marathon-LB will cause it to advertise *all* apps on their service ports (provided there are no app and port-specific overrides present in their app definition), regardless of whether they have an `HAPROXY_GROUP` label present in their app definition.

This is not secure-by-default because there may be instances of apps that are *never* meant to be advertised because they explicitly did not set an `HAPROXY_GROUP` label.

Please alter the matching strategy to only advertise apps that have `HAPROXY_GROUP` set in their app definition.

This issue is related to #402 in that we'd like to enforce an opt-in model whenever possible.

**Comment by brndnmtthws** [comment]
I've updated the docs in #410.

**Comment by vishnu2kmohan** [comment]
Thanks!
