### ISSUE TITLE
Container using a vhost over tcp / access Redis in a container from another container

### ISSUE THREAD

**Issue by rsiebeling** [mesosphere/marathon-lb#405]
Hi,

it doesn't seem possible to use tcp connection over a vhost.
Whenever I add the vhost to the configuration the mode changes to http.

I'd like to use Redis in a container and speak to it from another container, for this I would like to add a vhost to be able to find the specific Redis container (there could be multiple Redis containers on the same host). Is there another way to do this?

thanks,
Richard

**Comment by edsonmo** [comment]
I'm not sure but I think that if you use virtualhost it's just for http service, if you need to see your service from another container you have to use a DNS service. 

Sorry for my english.

**Comment by brndnmtthws** [comment]
VHost are strictly an HTTP specific feature.
