### ISSUE TITLE
503s when restarting or scaling down

### ISSUE THREAD

**Issue by DukeyToo** [mesosphere/marathon-lb#408]
We get some 503s and 504s when restarting a marathon app or when scaling down.  Is this unusual, or expected?  If this is expected, is there anything I can do either to the microservices or to haproxy or elb timings that would improve this?

We are running 1.4.2 with `--health-check` option, with microservices that shutdown very quickly, and behind an amazon ELB.  We're not using zdd, and don't want to (it doesn't fit with how we use the tools right now).

In a simple test of scaling down from 10 to 1 instances of a microservice under high load, we get hundreds of 503s and 504s, albeit for a very brief period.  

Looking at the code, it seems to me that I should expect this, because the microservices shut down very quickly and by the time the haproxy switch happens, the old backends have been MIA for a little while, and hence 503 or 504 responses?

**Comment by brndnmtthws** [comment]
This is actually a limitation of Marathon, not marathon-lb.

Here's one way to work around it: https://github.com/mesosphere/marathon-lb#zero-downtime-deployments
