### ISSUE TITLE
Route single vhost to multiple backends

### ISSUE THREAD

**Issue by cheapRoc** [mesosphere/marathon-lb#409]
We need to serve single vhost requests (`app.domain.com`) into Marathon LB and out to multiple backend micro services hosted somewhere on a DC/OS cluster. 

The proxy chain looks like this...

`http://app.domain.com/auth/tokens` => `172.17.0.2:12345/tokens`

All of the services join their parent domain under unique paths but their backends serve REST endpoints off the root. We want to maintain frontend namespacing at the load balancer but serve off the root on the backend.

Any idea which magic incantation of `HAPROXY_0_*` environment variables we need to use to do this? We just want to use something like the following [URL rewrite](https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html)...

```
acl is_auth path_beg -i /auth
http-request set-path /%[path] if is_auth
```

**Comment by brndnmtthws** [comment]
Route by path: https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_n_path

You probably also want to use proxy pass, too: https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_n_http_backend_proxypass_path

**Comment by cheapRoc** [comment]
@brndnmtthws That doesn't solve our problem. Using a `HAPROXY_<n>_HTTP_BACKEND_PROXY_PATH_PATH` of `/` continues to push our frontend path into the backend. So `/auth/tokens` remains unchanged to `/auth/tokens`. We need it to remove the `/auth` to remove the API endpoint namespace. Picking up what I'm putting down?

**Comment by brndnmtthws** [comment]
Change `HAPROXY_{n}_HTTP_BACKEND_PROXYPASS_PATH` to `/auth`, and you should get the behaviour you desire. Here's the regex: https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_http_backend_proxypass_glue

**Comment by cheapRoc** [comment]
That worked, thanks man!

We're a little perplexed as how one conceptualizes the cascading rulesets found in [Longhelp.md](https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md). But we'll take your word for it. 👍
