### ISSUE TITLE
Some of the marathon-lb config mapping which works on 1.2.1  is not working on 1.4.3

### ISSUE THREAD

**Issue by d2e** [mesosphere/marathon-lb#411]
Some of the service that we use on DCOS relies on haproxy rules for routing request.
This haproxy rules works just fine on marathon-lb 1.2.1 but it is not working on newer version of
marathon-lb 1.4.3
I am using following rule 
` "HAPROXY_0_HTTP_FRONTEND_ACL": " acl host_{cleanedUpHostname} hdr(host) -i {hostname}\n acl testing_{cleanedUpHostname} hdr(x-ads-testing) -m found\n use_backend {backend} if testing_{cleanedUpHostname} host_{cleanedUpHostname}\n",`

I also verified haproxy.cfg file on marathon-lb container these rule are not getting applied.

**Comment by brndnmtthws** [comment]
Try disabling the vhost map option, by removing the `--haproxy-map` from the MLB command line arguments.
