### ISSUE TITLE
setting HAPROXY_HTTP_FRONTEND_HEAD as env or label does nothing

### ISSUE THREAD

**Issue by craiggenner** [mesosphere/marathon-lb#420]
The subject says is all really.

I've set HAPROXY_HTTP_FRONTEND_HEAD as both a env and label when creating the marathon-lb application and it has no impact.

The same is also true for HAPROXY_HTTP*S*_FRONTEND_HEAD

I'm trying to add 'accept-proxy' to support `proxyprotocol` with the following:

"HAPROXY_HTTPS_FRONTEND_HEAD":"frontend marathon_https_in bind *:443 accept-proxy ssl {sslCerts} mode http"
"HAPROXY_HTTP_FRONTEND_HEAD":"frontend marathon_http_in bind *:80 accept-proxy mode http"

Am I doing something wrong?  How would I achieve this?

Running with mesosphere/marathon-lb:v1.5.0, marathon 1.3.10-1.0.627.ubuntu1404, mesos 1.1.0-2.0.107.ubuntu1404, and docker 1.13.1-0~ubuntu-trusty

**Comment by brndnmtthws** [comment]
Try using `HAPROXY_0_HTTP_FRONTEND_HEAD` or `HAPROXY_0_HTTPS_FRONTEND_HEAD` instead.

**Comment by craiggenner** [comment]
That didn't work, these are global options which I've set on the marathon-lb app.

The options you provided look like they should be set as a label on an app behind marathon-lb.

Any further thoughts?

**Comment by brndnmtthws** [comment]
Ah, if that's the case, you need to supply templates when you start MLB. Here's an example on how to do that:

https://github.com/mesosphere/marathon-lb/wiki#enabling-tls-v10

You just need to create a tarball with your templates, add that to the list of URIs, and it should work. See https://github.com/mesosphere/marathon-lb#deployment which mentions this.
