### ISSUE TITLE
cannot change haproxy config by add labels 

### ISSUE THREAD

**Issue by tanglianggithub** [mesosphere/marathon-lb#434]
I want to close some app's http-keep-alive in the backend. I did as follows.
![image](https://cloud.githubusercontent.com/assets/3445470/24079296/594d257a-0cbf-11e7-9e46-fbb1d4479a58.png)

but in the hostname:port/_haproxy_getconfig didn't show what I have set, as follows:
![image](https://cloud.githubusercontent.com/assets/3445470/24079300/7cfea796-0cbf-11e7-87d4-3cc6acb783ab.png)

my marathon-lb's config:
![image](https://cloud.githubusercontent.com/assets/3445470/24086825/7ac23848-0d51-11e7-8b17-ded31460a870.png)

Is there any thing wrong in my config?

In addition if I set **"HAPROXY_{0}_BACKEND_HTTP_OPTIONS":"  option forwardfor\n  no option http-keep-alive\n  http-request set-header X-Forwarded-Port %[dst_port]\n  http-request add-header X-Forwarded-Proto https if { ssl_fc }\n"** in my app labels which won't work also.

**Comment by jeid64** [comment]
I don't believe there should be {} surrounding the 0 in your label? Can you try 
HAPROXY_0_BACKEND_HTTP_OPTIONS instead?

**Comment by tanglianggithub** [comment]
@jeid64 I did that before u say that. It showed as follows:
![image](https://cloud.githubusercontent.com/assets/3445470/24131885/49df2dc2-0e2c-11e7-9903-c69ba5307885.png)


and marathon-lb's code is as follows , which has '{}', this is why add '{}': 
![image](https://cloud.githubusercontent.com/assets/3445470/24131911/71c90588-0e2c-11e7-9d6f-5d3796fdefe6.png)

**Comment by cepefernando** [comment]
Having the same issues, If I add the labels they are not added into HAProxy.

**Comment by paambaati** [comment]
@tanglianggithub @cepefernando Can you also include the `HAPROXY_0_MODE` label set to `http`? All `*_HTTP_*` labels work only when the app is set to `http` mode.

Also, @tanglianggithub, which version of `marathon-lb` is this? I don't see this code anywhere on master.

**Comment by jkoelker** [comment]
the `{0}` in the code is for the python string formatting that happens later on. To get the list of rendered options and their examples use `python3 ./marathon-lb --longhelp`. I agree that its super non-intuitive from looking at the code, but that's the way it works unfortunately.
