### ISSUE TITLE
Cannot add placement constraints in config

### ISSUE THREAD

**Issue by mimmus** [mesosphere/marathon-lb#437]
I have different public_agents to selectively expose services on different networks.

Id' like to specify placement constraints for different marathon-lb instances.
Currently, constraint property is not available.

Thanks for your attention

**Comment by jkoelker** [comment]
Currently since marathon-lb is just another marathon app, you can specify any constraints in the [`constraints`](https://mesosphere.github.io/marathon/docs/constraints.html) field of the deployment. I'm not sure what the status was at the time of reporting this issue. Apologies for the delay.

**Comment by mslee89** [comment]
I have a question.
The setting below is my marathon-lb json file
.
`{
  "marathon-lb": {
    "auto-assign-service-ports": false,
    "bind-http-https": true,
    "cpus": 4,
    "haproxy_global_default_options": "redispatch,http-server-close,dontlognull",
    "haproxy-group": "external",
    "haproxy-map": true,
    "instances": 1,
    "mem": 4096,
    "minimumHealthCapacity": 0.5,
    "maximumOverCapacity": 0.2,
    "name": "/system/marathon-lb-external",
    "parameters": [],
    "role": "slave_public",
    "strict-mode": false,
    "sysctl-params": "net.ipv4.tcp_tw_reuse=1 net.ipv4.tcp_fin_timeout=30 net.ipv4.tcp_max_syn_backlog=10240 net.ipv4.tcp_max_tw_buckets=400000 net.ipv4.tcp_max_orphans=60000 net.core.somaxconn=10000",
    "container-syslogd": false,
    "max-reload-retries": 10,
    "reload-interval": 10,
    "template-url": "",
    "marathon-uri": "http://marathon.mesos:8080",
    "secret_name": "",
    "constraints": [
      [
        "type",
        "CLUSTER",
        "system"
      ]
    ]
  }
}`

but It does not work.
Did I set it wrong?
