### ISSUE TITLE
marathon-lb stopped updating haproxy config when one of three marathon services deadlocked

### ISSUE THREAD

**Issue by jamiethermo** [mesosphere/marathon-lb#440]
We have three marathon servers running 1.3.6. We have one agent running marathon-lb v1.4.1. We had a leadership election on zookeeper that left marathon0 in an inconsistent state: it had lost leadership but did not reset. It did not accept new connections on its rest api.

The marathon-lb script appeared to hang. There were no stack-traces in the logs. However, it stopped producing any output, whereas before it would consistently report application updates every five minutes ('condition wait expired' .. 'fetching apps').

The last event written to the log was 'received event of type health_status_changed_event'.

**Comment by jamiethermo** [comment]
ok, this might be https://github.com/mesosphere/marathon-lb/issues/344

**Comment by jkoelker** [comment]
Closing for now, please reopen if it is still an issue.
