### ISSUE TITLE
HAPROXY_0_MODE TCP

### ISSUE THREAD

**Issue by mastermindg** [mesosphere/marathon-lb#449]
Why is marathon-lb still not able to set TCP Mode on Vhosts? This seems like a show-stopper for using this since enterprise networks are naturally cross-connected.

**Comment by ganeshkondal** [comment]
We are trying to configure vhosts with tcp traffic. Any update on this one?

**Comment by jkoelker** [comment]
vhosts are a HTTP (layer 7) specific concept. TCP mode is layer 4 which has no notion of vhosts only ips and ports.
