### ISSUE TITLE
Can't access websocket (ws://) url using marathon-lb

### ISSUE THREAD

**Issue by hamsal** [mesosphere/marathon-lb#459]
I have a container running a jupyter gateway which requires two urls to be accessible a http and websocket url. 

On localhost, for example, these urls are `http://127.0.0.1:8888` and `ws://127.0.0.1:8888`. 

When I start my app with marathon and ssh into the mesos slave running the container I can access both of these urls functionality using my client that makes requests to the jupyter gateway. Which tells me the jupyter gateway in the container is working fine. 

However when I am trying to access the jupyter gateway through the marathon load balancer my client tells me it can reach the `http://` url fine but it times out when trying to connect to the `ws://` url which I need to be able to access. 

I believe marathon-lb supports forwarding websockets without extra configuration so I am not sure what the issue is but I suspect it could do with the following haproxy config in my marathon app labels.

Labels:
```
HAPROXY_0_MODE=http
HAPROXY_0_PATH=/jupyter-gateway-container-path
HAPROXY_0_VHOST=ourwebsite.com
```

**Comment by willastronomer** [comment]
What did you do to resolve this?
