### ISSUE TITLE
Launching multiple instances from CLI

### ISSUE THREAD

**Issue by ensonik** [mesosphere/marathon-lb#46]
For the life of me, I can't get the package to launch with 2 instances. I've tried:

    dcos package install --options=public-lb-descriptor.json marathon-lb

Where the content of public-lb-descriptor.json reads as:

    {
      "id":"marathon-lb",
      "instances": 2
    }

To no avail. 

Scalling with the Marathon UI (using the Scale Application button) works fine ... but I need to script it.

**Comment by ensonik** [comment]
FYI: A curl request through the HTTP api works ... 

    curl -H "Content-Type: application/json" -X PUT -d '{"instances": 2}'  http://host/marathon/v2/apps/marathon-lb

**Comment by brndnmtthws** [comment]
Try this in your `public-lb-descriptor.json `:

```json
{
  "marathon-lb":{
    "instances":2
  }
}
```

**Comment by ensonik** [comment]
Doh.  Thx.
