### ISSUE TITLE
How can I set HA to IP and (not or) Host?

### ISSUE THREAD

**Issue by milla** [mesosphere/marathon-lb#468]
Now I know that 80 and 443 can be configured as below, how about if I want to expose specific port like 8083

> HAPROXY_0_MODE=http
> HAPROXY_1_MODE=https
> HAPROXY_0_GROUP=external
> HAPROXY_1_GROUP=external
> HAPROXY_1_VHOST=xx.xx.xx.xx,xxx.eastus.cloudapp.azure.com
> HAPROXY_0_VHOST=xx.xx.xx.xx,xxxx.eastus.cloudapp.azure.com

**Comment by lloesche** [comment]
There's the `HAPROXY_{n}_BIND_ADDR` option that allows you to bind a frontend to a specific IP and/or port.

E.g.
```
HAPROXY_0_BIND_ADDR=*:8083
```
or
```
HAPROXY_0_BIND_ADDR=123.123.123.123:80
```
