### ISSUE TITLE
Invalid HAPROXY_{n}_xxx template labels in one app can break haproxy config

### ISSUE THREAD

**Issue by matt-deboer** [mesosphere/marathon-lb#482]
In a cluster with many users, a single app containing bad `HAPROXY_{n}_xxx` template labels will result in a bad overall haproxy config.

The effect of this is that already started marathon-lb instances will stop updating, and new marathon-lb instances cannot start.

An example "bad label":
`HAPROXY_0_BACKEND_SERVER_OPTIONS`: `"  server {serverName} {host_ipv4}:{port}{cookieOptions}{healthCheckOptions}{otherOptions}  timeout server 600s"`

(this particular bad label was produced by attempting to edit it using the dcos ui, which removes some of the critical line endings from the string)

**Comment by zhoulouzi** [comment]
i got the same issue:
-----------------------------------
my "bad label":
HAPROXY_0_BACKEND_SERVER_OPTIONS= server {serverName} {host_ipv4}:8090{cookieOptions}{healthCheckOptions}{otherOptions}\n
-----------------
the result in haproxy.cfg:
backend release_dolphin_10069
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server 192_168_30_214_31309 192.168.30.214:8090\n
-----------------------------------
if i scale my app to 2 or more :
the result in haproxy.cfg will be:
backend release_dolphin_10069
  balance roundrobin
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server 192_168_30_214_31309 192.168.30.214:8090\n  server 192_168_30_215_31310 192.168.30.215:8090\n

**Comment by zhoulouzi** [comment]
i was wrong。 config in json mode ：
"HAPROXY_0_BACKEND_SERVER_OPTIONS": "  server {serverName} {host_ipv4}:8090{cookieOptions}{healthCheckOptions}{otherOptions}\n"
  it works well

**Comment by justinrlee** [comment]
I believe this is resolved - please let me know if I need to reopen.
