### ISSUE TITLE
fast haproxy reloads leak processes on systemd based systems

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon-lb#5]
This is just to track the upstream effort.
See https://github.com/haproxy/haproxy/issues/48

**Comment by lloesche** [comment]
The Problem still exists in https://github.com/mesosphere/marathon-lb/blob/master/marathon-update-haproxy.py#L869

**Comment by discordianfish** [comment]
@lloesche But marathon-lb isn't using the haproxy-systemd-wrapper. Do you think the same problem happens with the script here?

**Comment by lloesche** [comment]
@discordianfish it is if you're using it as a replacement for servicerouter.py which has been removed from the marathon repo. Not everyone runs Docker on their load balancer nodes. haproxy-systemd-wrapper is what's shipped with default RHEL7. So a `systemctl reload haproxy` will trigger the bug.

**Comment by lloesche** [comment]
Best option here is to not use the distributions haproxy package and run our Docker image instead. Problem has been reported upstream though.
