### ISSUE TITLE
how to get fixed and different host port and service port with host mode container

### ISSUE THREAD

**Issue by ninedouphy** [mesosphere/marathon-lb#500]
I want to move my services to mesos+marathon cluster, and use marathon-lb to load my docker services , but the service in my contailners use the address 127.0.0.1:port to access other service(can't not change). if use BRIDGE mode containers, it can't work right(because of error accessing 127.0.0.1) !
so i want to use HOST mode of container,  , and try to set fixed and different host port and service port ,How do i achieve that，any suggestion？
it should look like this :   serviceA(HOST mode) -> 127.0.0.1:10000(fixed servicePort) --haproxy--> 192.168.1.11:1234(fixed hostPort)-->serviceB(HOST mode)

**Comment by jkoelker** [comment]
Unfortunately this is out of the scope of marathon-lb. You may try using a sidecar container for ServiceA that runs `socat` to redirect the `localhost` traffic.
