### ISSUE TITLE
Ignoring `failed_health_check_event` event from marathon

### ISSUE THREAD

**Issue by ajays20078** [mesosphere/marathon-lb#507]
Can we not just ignore `failed_health_check_event` event from marathon as it will be followed up with a new task launch and HAProxy anyways maintains its own health checks to backends. We can save a unnecessary reload.

**Comment by jkoelker** [comment]
Hello, sorry the delay in getting to this. I think the latest code ignored the event as you suggested as it only listens for the specific events (https://github.com/mesosphere/marathon-lb/blob/master/marathon_lb.py#L230-L233). Please re-open this if I am mistaken.
