### ISSUE TITLE
Suspicious file system and process activity in Marathon-lb container

### ISSUE THREAD

**Issue by lfatty** [mesosphere/marathon-lb#529]
Hello there,
 
Recently, we notice few activities of Haproxy that our security tool flags as suspicious. I would like to understand some of haproxy activities inside the container. Are these activities normal?
 
For example we have seen something like: 

/usr/bin/python3.5 wrote a suspicious file to /marathon-lb/haproxy.cfg
 
/usr/bin/flock launched but is not found in the runtime model MD5:edd7ffadefe1b247cdbefe51b800524d. Full command: flock 200
 
High rate of processes events, reporting aggregation started
 
/usr/bin/bash wrote a suspicious file to /tmp/sh-thd.Owvhsg
 
/usr/bin/bash wrote a suspicious file to /tmp/sh-thd.Sj1cF9 (deleted)

**Comment by justinrlee** [comment]
Hey Lamin,

Sorry for the late reply here.  What tool are you using for security scanning?

I'm not sure why your tool is flagging haproxy.cfg as suspicious, but part of the core functionality of Marathon-LB is that it does the following:
-write a temporary HAProxy configuration file to /tmp/<some-random-filename>
-verify the HAProxy configuration file is valid
-if valid, write that to /marathon-lb/haproxy.cfg

Separately, the flock is used to basically handle passing port file descriptors from one instance of HAProxy to another.

So those are all per design.  Does this help?

Thanks!

**Comment by lfatty** [comment]
@justinrlee,

Thanks for the follow-up. We are using Twistlock. Is there a way we could screenshare so that we talk about this issue. Perhaps, I could tell you what i think is happening.

**Comment by jkoelker** [comment]
Hi I'm working on cleaning up the marathon-lb issue. Since the activity reported can be explained via the normal operation of maration-lb, I'm going to close this issue. If this is not the case please let me know.
