### ISSUE TITLE
Inject rules in HAProxy for services not managed by Marathon 

### ISSUE THREAD

**Issue by benfab** [mesosphere/marathon-lb#530]
Hello,

I would like to use the same HAProxy pair to reach _all_ my services, including the ones which are not deployed on Marathon. So, I am looking for a way to tell marathon-lb to write some default rules into haproxy.cfg to forward traffic to the services running outside of marathon.

Is that something already supported by marathon-lb? If yes, how can I do so?

Thank for your help!

**Comment by justinrlee** [comment]
Marathon-LB basically combines a bunch of different template strings into a single consolidated haproxy.cfg.  This is a bit hacky, but one thing I've done in the past is something like this:

The default `HAPROXY_HTTP_FRONTEND_HEAD` looks like this:
```

frontend marathon_http_in
  bind *:80
  mode http
```

You can add additional frontends/backends above this (note that other parts of the script will append content to this frontend, so you want to put content above, not below):

```
frontend custom
  bind *:8080
  mode http
  default_backend custom_backend

backend custom_backend
  mode http
  balance roundrobin
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server custom 10.10.10.10:80 check

frontend marathon_http_in
  bind *:80
  mode http
```

I think we're open to suggestions on more customization for Marathon-LB, as long as it's universally beneficial.  Might be worth adding a generic customizable global section.

**Comment by jkoelker** [comment]
Hi, I'm working on cleaning up the marathon-lb repo. The solution above is the right way to go for this. Since there isn't really a bug here, I'm going to close the issue.
