### ISSUE TITLE
HAPROXY_HTTPS_FRONTEND_HEAD overwritten on startup in mesosphere/marathon-lb:v1.7.0

### ISSUE THREAD

**Issue by joelstewart** [mesosphere/marathon-lb#531]
I volume mount the mesosphere/marathon-lb:v1.7.0 docker image to add a capture for a header.

  {
        "containerPath": "/marathon-lb/templates/HAPROXY_HTTP_FRONTEND_HEAD",
        "hostPath": "/......./marathon-lb/HAPROXY_HTTP_FRONTEND_HEAD",
        "mode": "RW"
      },

When the process starts up, it overwrites the changes I made to the template.

What is the proper way to control what goes into the 

frontend marathon_http_in
  bind *:80
  mode http
  .... insert capture configs here ...

**Comment by joelstewart** [comment]
I stopped using volume mount and used "fetch" in DC/OS json to load a tar containing a /templates dir.

{
      "uri": "file:///shared/paas/marathon-lb/mlb.tar.gz",
      "extract": true,
      "executable": false,
      "cache": false
    }

And I was able to supply my custom frontend marathon_http_in settings

I found the docs here:  https://github.com/mesosphere/marathon-lb/wiki#enabling-tls-v10 

More verbage would have been helpful here:  https://github.com/mesosphere/marathon-lb#templates

**Comment by jkoelker** [comment]
Hi, sorry for the delay in getting to this issue. It defiantly should not be overwriting the tempalte. One way to make sure of this is to mount the template in readonly. I would make sure that in the logs it is stating that it overriding the `HAPROXY_HTTP_FRONTEND_HEAD` from the file. If it does not then its not finding that file (https://github.com/mesosphere/marathon-lb/blob/v1.7.0/config.py#L779-L783).

The doc you reference has now been updated in https://github.com/mesosphere/marathon-lb/commit/b8efe88e2c2d48a58221b61dcd2614327fde5e60.
