### ISSUE TITLE
HAPROXY_0_BACKEND_HEAD newline character cause problem

### ISSUE THREAD

**Issue by agate** [mesosphere/marathon-lb#542]
I try to follow this way to increase my backend service's timeout: https://github.com/mesosphere/marathon-lb/wiki#setting-timeout-for-long-lived-socket-connections

I found haproxy config be generated properly from: `:9090/_haproxy_getconfig` which is good. But I found my marathon application failed to start up. It's because in the label `HAPROXY_0_BACKEND_HEAD` contains `\n` which cause mesos not able to launch docker application(mesos try to set this lable as a docker's env var). The error shows in mesos: `docker: poorly formatted environment: variable 'balance {balance}' has white spaces.`

So I try to avoid use `\n` in label `HAPROXY_0_BACKEND_HEAD`. But that cause haproxy config syntax error.

Any help?

**Comment by justinrlee** [comment]
Hi,
Where are you configuring this?  The labels from that example should be configured as `labels` on the target application, not on Marathon-LB.  Also, they should be configured as `labels`, not as environment variables.

Can you show me the marathon json definition you're trying to use?

Thanks,
Justin Lee

**Comment by joecox** [comment]
I am having the same issue.  I set the `HAPROXY_0_BACKEND_HEAD` in my app to:
```json
{
  "labels": {
    "HAPROXY_0_BACKEND_HEAD": "backend {backend}\n  balance {balance}\n  mode {mode}\n  timeout server 30m\n  timeout client 30m\n"
  }
}
```

My app fails to start.  In my app's stderr, I see:
```
docker: poorly formatted environment: variable 'balance {balance}' has white spaces.
```

To the best of my understanding, Mesos tries to inject the environment variable `MARATHON_APP_LABEL_HAPROXY_0_BACKEND_HEAD`.  My guess is this is where it fails.

Mesos version: 1.2.0
Marathon version: 1.4.11

**Comment by agate** [comment]
OK. I confirmed that this is because of the mesos version. I upgraded my mesos slave version to `1.3.2` and it solved the problem.
