### ISSUE TITLE
Support adding a custom header of the backend to the response

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon-lb#55]
ie:

`X-haproxy-backend: hostname.of.mesos.agent:port_of_app`

This would ideally be a global flag for marathon-lb, and would ease troubleshooting in certain instances for http applications. If you like the idea, let me know and I can likely come up with a patch to enable it (disabled by default).

**Comment by SEJeff** [comment]
@brndnmtthws or would you prefer I do something kind of like in your [blue green deploy branch docs](https://github.com/mesosphere/marathon-lb/tree/blue-green-deployment#overridable-templates)?

It seems like being able to do something like this globally would be more desirable and consistent, but I can see a case for forcing users to add it to their app labels if they want this.

**Comment by brndnmtthws** [comment]
I think in your case, passing your own templates would make the most sense.

**Comment by SEJeff** [comment]
Cool, thanks and sorry for the issue spam.

**Comment by scalp42** [comment]
@SEJeff any chance you could share the template for it ?

**Comment by SEJeff** [comment]
@scalp42 I'll probably be sending a few PRs down the road to make this a bit nicer, but I needed to change the healthcheck to the more lightweight HEAD requests and did this:


```json
    "labels": {
        "HAPROXY_0_MODE": "http",
        "HAPROXY_GROUP": "external",
        "HAPROXY_0_VHOST": "my-mesos-dns-task-name.mesos",
        "HAPROXY_0_BACKEND_HTTP_HEALTHCHECK_OPTIONS": "  option  httpchk HEAD {healthCheckPath}\n  timeout check {healthCheckTimeoutSeconds}s\n  http-response add-header X-Backend-Name %s\n"
    },  
```

Search [this document](http://www.haproxy.org/download/1.5/doc/configuration.txt) via `<CTRL>-f` for:

`Please refer to the table below for currently defined variables`

This did the trick just fine for me.

**Comment by scalp42** [comment]
Thanks a lot @SEJeff, greatly appreciated.
