### ISSUE TITLE
%{+Q} breaks HAPROXY_HTTPS_FRONTEND_HEAD when generating config

### ISSUE THREAD

**Issue by frothlauf** [mesosphere/marathon-lb#553]
Hey Guys,

I am using marathon-lb via "docker run" command and currently I am experiencing a problem when I include the following in HAPROXY_HTTPS_FRONTEND_HEAD environment variable:

```
.....
http-request set-header X-SSL-Client-CN %{+Q}[sl_c_s_dn(cn)]
.....
```

Resulting in the error:

```
2018-02-09 09:07:32,619 marathon_lb: generating config
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1962, in <module>
    args.haproxy_map)
  File "/marathon-lb/marathon_lb.py", line 1528, in regenerate_config
    app_map_array, config_file)
  File "/marathon-lb/marathon_lb.py", line 349, in config
    sslCerts=" ".join(map(lambda cert: "crt " + cert, _ssl_certs))
KeyError: '+Q'
```

As soon as i remove the "%{+Q}" which is needed to make the Header filled with data in the right format, everything is starting quite usual. Already tried to escape several characters, while I thought this could be the reason. 

Would be great if someone else had this problem before and could share his experience with me. Thanks in advance!

**Comment by justinrlee** [comment]
Not sure if this will work, but can you try doubling the brackets?

```
http-request set-header X-SSL-Client-CN %{{+Q}}[sl_c_s_dn(cn)]
```

**Comment by frothlauf** [comment]
Thanks for your response. This actually solved the problem. Thanks! 
I already tried to escape any character, tried to double "%" - yet the double brackets did the trick. Thanks a lot!
