### ISSUE TITLE
haproxy was not able up and running when deploying marathon-lb v1.5.0

### ISSUE THREAD

**Issue by memorandump** [mesosphere/marathon-lb#587]
2018-05-22 09:26:20,274 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1510, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1345, in get_apps
    get_health_check(app, i),
  File "/marathon-lb/marathon_lb.py", line 1209, in get_health_check
    for check in app['healthChecks']:
KeyError: 'healthChecks'
cat: /tmp/haproxy.pid: No such file or directory

Please refer the attachments for more info

[marathon-lb-conf.txt](https://github.com/mesosphere/marathon-lb/files/2029794/marathon-lb-conf.txt)
[stderr.txt](https://github.com/mesosphere/marathon-lb/files/2029789/stderr.txt)
[stdout.txt](https://github.com/mesosphere/marathon-lb/files/2029790/stdout.txt)

**Comment by jkoelker** [comment]
Sorry for the delay in getting to this. This was fixed in v1.9.0 in commit https://github.com/mesosphere/marathon-lb/commit/1303b531c00036e4d86d53b0070fde6d84c3893a.
