### ISSUE TITLE
ZDD broken with the beta features merge #569

### ISSUE THREAD

**Issue by DrMurx** [mesosphere/marathon-lb#588]
#569 broke `zdd.py` - it's going to stuck in an endless loop:

Since haproxy isn't spawned as a daemon anymore, it always has at least 2 processes in the process list. Therefore, the check for the number of haproxy instances in method `check_haproxy_reloading` always returns a value greater than 1.

**Comment by jkoelker** [comment]
fixed via https://github.com/mesosphere/marathon-lb/pull/598
