### ISSUE TITLE
unbound variable PORTS v1.1.0

### ISSUE THREAD

**Issue by guidob** [mesosphere/marathon-lb#59]
I'm getting an error when trying to upgrade to v1.1.0:

/marathon-lb/run: line 6: PORTS: unbound variable

Am I missing something?

**Comment by pgraemer** [comment]
try passing an PORTS env to docker, normally marathon would do this i guess.

> docker run -P -e "PORTS=10000" mesosphere/marathon-lb:v1.1.0 poll -m http://master.mesos:8080 --health-check --group external

currently you are going to run into #60 / #57 with the public docker images

**Comment by brndnmtthws** [comment]
As @pgraemer mentioned, if you use the built-in `run` script, you'll need to pass an env var that contains a comma separated list of the ports HAProxy binds to.

**Comment by brndnmtthws** [comment]
I'll add a more helpful error message for this.

**Comment by guidob** [comment]
@brndnmtthws,

Could explain the reasoning behind this? I would guess without any background information a sensible default would be 80,443,9090. Or docker inspect the HostPort's that are being mapped?

**Comment by brndnmtthws** [comment]
It's required for the firewall rules here: https://github.com/mesosphere/marathon-lb/blob/master/service/haproxy/run#L17-L21

For more background on why we do this, have a look here:
- https://github.com/mesosphere/marathon-lb#zero-downtime-deployments
- http://www.haproxy.org/download/1.6/doc/management.txt, under "4. Stopping and restarting HAProxy"
- http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html

**Comment by guidob** [comment]
@brndnmtthws,

Awesome, really happy this change made it through. Thanks!
I still wonder if a default 80,443,9090 would make sense, but I leave that up to you. ;)

**Comment by MacTynow** [comment]
Sorry for the duplicate.

Does this mean you need to specify all the ports you want to use? Say for exemple I have 30 services running in marathon with randomly assigned ports, is there any way I can specify a range?

**Comment by brndnmtthws** [comment]
It's not strictly required, and you must list _all_ the ports, or just one (if you want). See my comment here: https://github.com/mesosphere/marathon-lb/issues/59#issuecomment-182505469

**Comment by MacTynow** [comment]
It is really not convenient. I would like to be able to list the marathon default range, since I do not control the services that are deployed, the number of them and the ports they will use. If it's not required, how to bypass it?

**Comment by brndnmtthws** [comment]
You can supply your own script instead, or just specify any port.

**Comment by MacTynow** [comment]
Alright, I'll do it this way. Thanks for the clarification and the help!
