### ISSUE TITLE
Deb package libcurl3 is needed at runtime for libcurl.so.4, but is uninstalled on line 95 of the Dockerfile

### ISSUE THREAD

**Issue by chriskite** [mesosphere/marathon-lb#593]

**Comment by chriskite** [comment]
This causes marathon-lb to fail when the docker image is run, with this error:
`Jul 17 21:27:28 ip-10-42-131-182.ec2.internal bash[2753]: ImportError: libcurl.so.4: cannot open shared object file: No such file or directory
Jul 17 21:27:28 ip-10-42-131-182.ec2.internal bash[2753]: [ALERT] 197/212728 (3298) : Cannot open configuration file/directory /marathon-lb/haproxy.cfg : No such file or directory
Jul 17 21:27:29 ip-10-42-131-182.ec2.internal bash[2753]: down: /marathon-lb/service/haproxy: 1s, normally up, want up
Jul 17 21:27:29 ip-10-42-131-182.ec2.internal bash[2753]: Traceback (most recent call last):
Jul 17 21:27:29 ip-10-42-131-182.ec2.internal bash[2753]:   File "/marathon-lb/marathon_lb.py", line 44, in <module>
Jul 17 21:27:29 ip-10-42-131-182.ec2.internal bash[2753]:     import pycurl
`

I fixed this by reinstalling libcurl3 at the end of the Dockerfile, at the same time as python3 is reinstalled.

**Comment by chriskite** [comment]
It also looks like something from curl4 openssl is needed at runtime as well:

```
ImportError: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/local/lib/python3.6/dist-packages/pycurl.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by hansgogia** [comment]
Submitted a PR #597 changing the Dockerfile. Debian buster (Debian 10) doesn't have libcurl3 anymore in its repositories hence, replacing the package with the new version. Make the change in Dockerfile, build and run the new image. Should work fine.
