### ISSUE TITLE
Follow standby redirects

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon-lb#594]
In Marathon 1.7.x, Marathon will be sending 302 redirect responses when requesting /v2/events from a non-leader. Marathon-lb needs to be updated to follow these redirects.

**Comment by paambaati** [comment]
@timcharper I can send a PR for this. Can you link me to a relevant Marathon PR or commit? I tried looking but I couldn't find any!

**Comment by paambaati** [comment]
@timcharper NVM, found it.

Original Marathon JIRA card → https://jira.mesosphere.com/projects/MARATHON/issues/MARATHON-7178

Feature branch → https://github.com/mesosphere/marathon/compare/inc/events-redirect

**Comment by paambaati** [comment]
@timcharper Also, FYI, the code in your branch returns a `302`, not a `301`.

> In Marathon 1.7.x, Marathon will be sending 301

**Comment by timcharper** [comment]
@paambaati Thanks for the clarification!
