### ISSUE TITLE
Make marathon-lb available for all supported linux distributions

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon-lb#6]
It is possible to install mesos and marathon as native package.
In order to make marathon-lb available for those users, it should be available as native package as well.

**Comment by discordianfish** [comment]
@aquamatthias Native packaging isn't a goal of this this (yet), but people are free to use the haproxy update script directly.

**Comment by lloesche** [comment]
Since we now compile a custom haproxy with lua support for the container it's not really practical to package this up. We should rather steer people towards using the Docker image.
