### ISSUE TITLE
marathon-lb doesn't start anymore on CoreOS 1855

### ISSUE THREAD

**Issue by mimmus** [mesosphere/marathon-lb#605]
Upgrading from CoreOS 1688 to 1855 breaks marathon-lb: it doesn't start anymore because its health-check fails:
`health_checker.cpp:316] HTTP health check for task 'marathon-lb.85f8c1d7-e0fd-11e8-ac8a-ce05aed0598c' failed: curl exited with status 7: curl: (7) Failed to connect to 127.0.0.1 port 9090: Connection refused `

Rolling back to 1688 solves the issue but 1855 is currently the latest stable

**Comment by jkoelker** [comment]
As you know by now, this was due to `containerd` launching on 10010 it was fixed in a later release of coreos: https://github.com/coreos/bugs/issues/2524
