### ISSUE TITLE
Support routing based on path prefix (suffix)

### ISSUE THREAD

**Issue by deric** [mesosphere/marathon-lb#64]
I'd like to implement rules that would route requests to different backends based on request URI prefix based on `acl path_beg` (or suffix if we want to make it more general - `path_end`). HAProxy config:

```
frontend parent_80
  bind *:80
  acl path_backendA path_beg /prefixA
  use_backend backendA_10002 if path_path_backendA

  acl path_backendB path_beg /prefixB
  use_backend backendB_10003 if path_path_backendB
  // when to rule matches, we'll use default backend
  use_backend parent_80
  
... (standard backend configuration)
```
Each of backends would need to specify its parent e.g. `HAPROXY_PARENT` and then prefix `HAPROXY_0_PATH_PREFIX`.

Does this make sense to you? Would you accept a PR for such feature?

**Comment by brndnmtthws** [comment]
Sounds great to me :grinning:  PRs welcome!

**Comment by lloesche** [comment]
@deric great suggestion! We already have the default catchall listeners on tcp/80 and tcp/443 where your code could be added. Looking forward to your PR!

**Comment by fanzhiwei2015** [comment]
@deric, I am looking for this feature, would you please specify more details how to use it? 

thanks a lot,

**Comment by brndnmtthws** [comment]
See #86.
