### ISSUE TITLE
Possible mistake in the documentation about "long-lived socket connection"

### ISSUE THREAD

**Issue by Morsicus** [mesosphere/marathon-lb#648]
Hey there!

Opening this issue about https://github.com/mesosphere/marathon-lb/wiki#setting-timeout-for-long-lived-socket-connections.

In this example, `timeout client` is defined as backend configuration. Following this [HAproxy Documentation](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#timeout%20client) it seems not to be available in `backend`. 

WDYT?

**Comment by jkoelker** [comment]
Yep, looks like it was a copy paste error from the `defaults` section. I updated the section in question.  Thanks!
