### ISSUE TITLE
Possibly wrong "long lived socket" configuration documentation

### ISSUE THREAD

**Issue by groyoh** [mesosphere/marathon-lb#649]
We recently configured our marathon-lb to have HAProxy in front of our Postgres databases. We started seeing some timeout on our connections between our micro services and our database. After some investigation, we decided to follow the [long-lived connection documentation](https://github.com/mesosphere/marathon-lb/wiki#setting-timeout-for-long-lived-socket-connections) and set the `timeout server` to a big value like `999999m`. Despite that, we kept on seeing connection timeout after around 1h. I investigated further by sniffing the TCP connection and saw that after exactly 1h HAProxy initiated a `FIN`. This lead me to look deeper into the HAProxy and realized that this matched perfectly [the default `timeout tunnel`](https://github.com/mesosphere/marathon-lb/blob/master/Longhelp.md#haproxy_head) configuration which is `3600s`. 

By looking at HAProxy documentation, I noticed that [timeout tunnel](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#timeout%20tunnel) is the actual timeout used when non-HTTP TCP connections are established:

> The tunnel timeout applies when a bidirectional connection is established
between a client and a server, and the connection remains inactive in both
directions. This timeout supersedes both the client and server timeouts once
the connection becomes a tunnel. In TCP, this timeout is used as soon as no
analyser remains attached to either connection (eg: tcp content rules are
accepted).

We then change our config to use the `timeout tunnel` instead of `timeout server` and this solved our timeout issues. Therefore I think the wiki should be updated as follows:

```diff
{
  "id":"app",
  "labels":{
    "HAPROXY_GROUP":"external",
-    "HAPROXY_0_BACKEND_HEAD":"backend {backend}\n  balance {balance}\n  mode {mode}\n  timeout server 30m\n"
+    "HAPROXY_0_BACKEND_HEAD":"backend {backend}\n  balance {balance}\n  mode {mode}\n  timeout tunnel 30m\n"
  }
}
```

**Comment by jkoelker** [comment]
You are absolutely correct it should be `timeout tunnel`. I have updated the [wiki](https://github.com/mesosphere/marathon-lb/wiki#setting-timeout-for-long-lived-socket-connections) as suggested. Thanks for taking the time to research it and report it!
