### ISSUE TITLE
will not deploy on marathon user service

### ISSUE THREAD

**Issue by mikestaub** [mesosphere/marathon-lb#69]
I was told that it is generally not a good idea to run my web app and services on the native DCOS marathon service. I would like to use this package to load balance HTTP traffic and do service discovery on my user marathon service.

However when I try to run "dcos package install marathon-lb" with config marathon.url set to my user marathon service, it just hangs in the "waiting" state. 

Is this package only meant to be run on the native marathon service?

**Comment by ensonik** [comment]
Off topic (sorry): @mikestaub Do you have a reference for this:

> I was told that it is generally not a good idea to run my web app and services on the native DCOS marathon service.

I'm currently running everything on the native DCOS marathon and haven't come across anything that says to do otherwise.

**Comment by mikestaub** [comment]
Sure, I was told by thomas.mesosphere (@pyronicide) on the DCOS slack channel at 9:59am on Dec 22nd.

There is also this doc: https://docs.mesosphere.com/manage-service/service-tutorials/marathon-add-user/

**Comment by ensonik** [comment]
Thanks Mike.

**Comment by brndnmtthws** [comment]
Are you referring to a MoM (Marathon on Marathon) setup? Marathon-lb will indeed work with MoM, but you'll have to do a few configuration changes to make it work correctly (point marathon-lb to the correct Marathon).

**Comment by brndnmtthws** [comment]
Closing this for now. Feel free to reopen if you have further questions.
