### ISSUE TITLE
"--listening" documentation is highly confusing

### ISSUE THREAD

**Issue by eLvErDe** [mesosphere/marathon-lb#70]
Hllo guys,

It tooks me some time to get the callback mode working because of this --help snippet:

```
  --listening LISTENING, -l LISTENING
                        The address this script listens on for marathon events
                        (default: None)
```

After polling the office, everybody agrees: what should be set here is something like "127.0.0.1:8080" or "0.0.0.0:82".
But this setting doesn't work. After dumping variable inside the code, I figured out the following code did not work:

```
    listen_uri = parse.urlparse(listen_addr)
    httpd = make_server(listen_uri.hostname, listen_uri.port, wsgi_app)
```

listen_uri got no hostname attr because the parsing failed. I had to set "---listening=http://0.0.0.0:8080" to get it working.

Btw, README displayed here at github doesn't talk at all about this --listening parameter (give a try with ctrl+f ;))

Thanks,

Adam.

**Comment by brndnmtthws** [comment]
Noted!

https://github.com/mesosphere/marathon-lb/commit/08a9201711346aa37b3b6957efee5e46d72e51b6
