### ISSUE TITLE
does it support proxypass?

### ISSUE THREAD

**Issue by fanzhiwei2015** [mesosphere/marathon-lb#75]
I have been looking for the proxy pass function for marathon-lb in internet, however don't see an example.

May I know if it's possible? and how? thanks

**Comment by lloesche** [comment]
Not out of the box but haproxy (the load balancer marathon-lb uses) supports something similar. Check http://blog.haproxy.com/2014/04/28/howto-write-apache-proxypass-rules-in-haproxy/ for more info.

**Comment by fanzhiwei2015** [comment]
thanks for the reply, yes, I saws this as well, but how can we make it work with marathon app automatically? I also see this marathon-lb issues , and it sounds similar to the proxypass. https://github.com/mesosphere/marathon-lb/issues/64

**Comment by LeePorte** [comment]
I'm actually working on creating a PR for this at the minute.

**Comment by LeePorte** [comment]
Updated PR post project restructure https://github.com/mesosphere/marathon-lb/pull/137
