### ISSUE TITLE
overall confusion on requirements and usage

### ISSUE THREAD

**Issue by albertsj1** [mesosphere/marathon-lb#76]
What are the requirements for running the marathon-lb as a docker container via Marathon/Mesos?  Are any special docker permissions required or special paths that need to be mounted from the host? It seems to require access to run iptables. Is this correct?
Is the haproxy web ui exposed?

Thanks

**Comment by pgraemer** [comment]
the haproxy stats can be accessed via: <host>:9090/haproxy?stats by default

an minimal example for marathon config can be:

```json
{
    "id": "/marathon-lb",
    "cpus": 1,
    "mem": 128.0,
    "instances": 1,
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "mesosphere/marathon-lb:v1.0.1",
            "network": "HOST",
            "forcePullImage": false
        }
    }
}
```

I haven't tried it with Docker 1.10 yet so i cannot tell if you have to apply custom seccomp rules. I'd say you don't have to.

**Comment by albertsj1** [comment]
@pgraemer Thanks for the reply.  In my test, I was using bridged networking. I'll give it a try using HOST networking.  I don't think that would allow the container access to IPTables though and I can see it's trying to modify IPTables rules here: https://github.com/mesosphere/marathon-lb/blob/master/service/haproxy/run#L20

**Comment by pgraemer** [comment]
looks like i missed some changes in the current master. 
have you tried using privileged mode? see [README](https://github.com/mesosphere/marathon-lb#zero-downtime-deployments)

i updated my last comment.

**Comment by albertsj1** [comment]
I read that but completely missed the part about privileged mode with blue/green deployments.  Thanks for pointing it out.

**Comment by albertsj1** [comment]
Got things working.  I needed to add privileged mode, use HOST networking, and in my AWS environment, I had to make sure the public IPs of the mesos slaves could all communicate with each other over the public IP.
Thanks again for your help.
