### ISSUE TITLE
What is the PORTS variable used for?

### ISSUE THREAD

**Issue by MacTynow** [mesosphere/marathon-lb#85]
Hi all,

This piece of code : 
```
if [ -n "${PORTS-}" ]; then
  echo $PORTS > $HAPROXY_SERVICE/env/PORTS
else
  echo "Define $PORTS with a comma-separated list of ports to which HAProxy binds" >&2
  exit 1
fi
```

Is making my container crash with the following error :
`/marathon-lb/run: line 10: PORTS: unbound variable`

What is it used for ? I can't find any reference to this env/PORTS file anywhere in the code : https://github.com/mesosphere/marathon-lb/search?utf8=%E2%9C%93&q=env%2FPORTS

Thanks!

**Comment by moderation** [comment]
I can confirm that I am getting this error also.

**Comment by pgraemer** [comment]
See issue #59
