### ISSUE TITLE
Different path routing on same multiple host

### ISSUE THREAD

**Issue by rvalkenaers** [mesosphere/marathon-lb#99]
Is it not possible to use 2 backends on 1 virtual host and do the routing based on path

For example:
app1:
HAPROXY_VHOST = app.example.com
HAPROXY_PATH = /app1
app2:
HAPROXY_VHOST = app.example.com
HAPROXY_PATH = /app2

Both acl names in the haproxy.cfg will be called path_app_example.com so the first one always get selected.

Both requests app.example.com/app1 and app.example.com/app2 go to app1

Possible solution: include marathon app id in acl name.

**Comment by brndnmtthws** [comment]
Good catch. Created a PR to address this.

**Comment by rvalkenaers** [comment]
Thanks for the fix. It's working great for http.

Is it also possible to do this for https_in frontend. I think it's already possible but I don't seem to get it working.

Do I have to de someting with HAPROXY_HTTPS_FRONTEND_ACL_WITH_PATH?

**Comment by cecemel** [comment]
+1

**Comment by brndnmtthws** [comment]
Looks like another bug. Should be fixed with #102.
